// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ClusterGroup struct {
	pulumi.CustomResourceState

	Config      pulumi.StringMapOutput `pulumi:"config"`
	Description pulumi.StringOutput    `pulumi:"description"`
	Name        pulumi.StringOutput    `pulumi:"name"`
	Remote      pulumi.StringPtrOutput `pulumi:"remote"`
}

// NewClusterGroup registers a new resource with the given unique name, arguments, and options.
func NewClusterGroup(ctx *pulumi.Context,
	name string, args *ClusterGroupArgs, opts ...pulumi.ResourceOption) (*ClusterGroup, error) {
	if args == nil {
		args = &ClusterGroupArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ClusterGroup
	err = ctx.RegisterPackageResource("incus:index/clusterGroup:ClusterGroup", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetClusterGroup gets an existing ClusterGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetClusterGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ClusterGroupState, opts ...pulumi.ResourceOption) (*ClusterGroup, error) {
	var resource ClusterGroup
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/clusterGroup:ClusterGroup", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ClusterGroup resources.
type clusterGroupState struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Name        *string           `pulumi:"name"`
	Remote      *string           `pulumi:"remote"`
}

type ClusterGroupState struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
}

func (ClusterGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterGroupState)(nil)).Elem()
}

type clusterGroupArgs struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Name        *string           `pulumi:"name"`
	Remote      *string           `pulumi:"remote"`
}

// The set of arguments for constructing a ClusterGroup resource.
type ClusterGroupArgs struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
}

func (ClusterGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterGroupArgs)(nil)).Elem()
}

type ClusterGroupInput interface {
	pulumi.Input

	ToClusterGroupOutput() ClusterGroupOutput
	ToClusterGroupOutputWithContext(ctx context.Context) ClusterGroupOutput
}

func (*ClusterGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterGroup)(nil)).Elem()
}

func (i *ClusterGroup) ToClusterGroupOutput() ClusterGroupOutput {
	return i.ToClusterGroupOutputWithContext(context.Background())
}

func (i *ClusterGroup) ToClusterGroupOutputWithContext(ctx context.Context) ClusterGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterGroupOutput)
}

type ClusterGroupOutput struct{ *pulumi.OutputState }

func (ClusterGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterGroup)(nil)).Elem()
}

func (o ClusterGroupOutput) ToClusterGroupOutput() ClusterGroupOutput {
	return o
}

func (o ClusterGroupOutput) ToClusterGroupOutputWithContext(ctx context.Context) ClusterGroupOutput {
	return o
}

func (o ClusterGroupOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ClusterGroup) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o ClusterGroupOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterGroup) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o ClusterGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterGroup) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o ClusterGroupOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterGroup) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterGroupInput)(nil)).Elem(), &ClusterGroup{})
	pulumi.RegisterOutputType(ClusterGroupOutput{})
}
