// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ClusterGroupMember struct {
	pulumi.CustomResourceState

	ClusterGroup pulumi.StringOutput    `pulumi:"clusterGroup"`
	Member       pulumi.StringOutput    `pulumi:"member"`
	Remote       pulumi.StringPtrOutput `pulumi:"remote"`
}

// NewClusterGroupMember registers a new resource with the given unique name, arguments, and options.
func NewClusterGroupMember(ctx *pulumi.Context,
	name string, args *ClusterGroupMemberArgs, opts ...pulumi.ResourceOption) (*ClusterGroupMember, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterGroup == nil {
		return nil, errors.New("invalid value for required argument 'ClusterGroup'")
	}
	if args.Member == nil {
		return nil, errors.New("invalid value for required argument 'Member'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource ClusterGroupMember
	err = ctx.RegisterPackageResource("incus:index/clusterGroupMember:ClusterGroupMember", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetClusterGroupMember gets an existing ClusterGroupMember resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetClusterGroupMember(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ClusterGroupMemberState, opts ...pulumi.ResourceOption) (*ClusterGroupMember, error) {
	var resource ClusterGroupMember
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/clusterGroupMember:ClusterGroupMember", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ClusterGroupMember resources.
type clusterGroupMemberState struct {
	ClusterGroup *string `pulumi:"clusterGroup"`
	Member       *string `pulumi:"member"`
	Remote       *string `pulumi:"remote"`
}

type ClusterGroupMemberState struct {
	ClusterGroup pulumi.StringPtrInput
	Member       pulumi.StringPtrInput
	Remote       pulumi.StringPtrInput
}

func (ClusterGroupMemberState) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterGroupMemberState)(nil)).Elem()
}

type clusterGroupMemberArgs struct {
	ClusterGroup string  `pulumi:"clusterGroup"`
	Member       string  `pulumi:"member"`
	Remote       *string `pulumi:"remote"`
}

// The set of arguments for constructing a ClusterGroupMember resource.
type ClusterGroupMemberArgs struct {
	ClusterGroup pulumi.StringInput
	Member       pulumi.StringInput
	Remote       pulumi.StringPtrInput
}

func (ClusterGroupMemberArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterGroupMemberArgs)(nil)).Elem()
}

type ClusterGroupMemberInput interface {
	pulumi.Input

	ToClusterGroupMemberOutput() ClusterGroupMemberOutput
	ToClusterGroupMemberOutputWithContext(ctx context.Context) ClusterGroupMemberOutput
}

func (*ClusterGroupMember) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterGroupMember)(nil)).Elem()
}

func (i *ClusterGroupMember) ToClusterGroupMemberOutput() ClusterGroupMemberOutput {
	return i.ToClusterGroupMemberOutputWithContext(context.Background())
}

func (i *ClusterGroupMember) ToClusterGroupMemberOutputWithContext(ctx context.Context) ClusterGroupMemberOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterGroupMemberOutput)
}

type ClusterGroupMemberOutput struct{ *pulumi.OutputState }

func (ClusterGroupMemberOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterGroupMember)(nil)).Elem()
}

func (o ClusterGroupMemberOutput) ToClusterGroupMemberOutput() ClusterGroupMemberOutput {
	return o
}

func (o ClusterGroupMemberOutput) ToClusterGroupMemberOutputWithContext(ctx context.Context) ClusterGroupMemberOutput {
	return o
}

func (o ClusterGroupMemberOutput) ClusterGroup() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterGroupMember) pulumi.StringOutput { return v.ClusterGroup }).(pulumi.StringOutput)
}

func (o ClusterGroupMemberOutput) Member() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterGroupMember) pulumi.StringOutput { return v.Member }).(pulumi.StringOutput)
}

func (o ClusterGroupMemberOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ClusterGroupMember) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterGroupMemberInput)(nil)).Elem(), &ClusterGroupMember{})
	pulumi.RegisterOutputType(ClusterGroupMemberOutput{})
}
