// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCluster(ctx *pulumi.Context, args *GetClusterArgs, opts ...pulumi.InvokeOption) (*GetClusterResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetClusterResult
	err = ctx.InvokePackage("incus:index/getCluster:getCluster", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCluster.
type GetClusterArgs struct {
	Remote *string `pulumi:"remote"`
}

// A collection of values returned by getCluster.
type GetClusterResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id          string                       `pulumi:"id"`
	IsClustered bool                         `pulumi:"isClustered"`
	Members     map[string]GetClusterMembers `pulumi:"members"`
	Remote      *string                      `pulumi:"remote"`
}

func GetClusterOutput(ctx *pulumi.Context, args GetClusterOutputArgs, opts ...pulumi.InvokeOption) GetClusterResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetClusterResultOutput, error) {
			args := v.(GetClusterArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetClusterResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getCluster:getCluster", args, GetClusterResultOutput{}, options).(GetClusterResultOutput), nil
		}).(GetClusterResultOutput)
}

// A collection of arguments for invoking getCluster.
type GetClusterOutputArgs struct {
	Remote pulumi.StringPtrInput `pulumi:"remote"`
}

func (GetClusterOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClusterArgs)(nil)).Elem()
}

// A collection of values returned by getCluster.
type GetClusterResultOutput struct{ *pulumi.OutputState }

func (GetClusterResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetClusterResult)(nil)).Elem()
}

func (o GetClusterResultOutput) ToGetClusterResultOutput() GetClusterResultOutput {
	return o
}

func (o GetClusterResultOutput) ToGetClusterResultOutputWithContext(ctx context.Context) GetClusterResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetClusterResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetClusterResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetClusterResultOutput) IsClustered() pulumi.BoolOutput {
	return o.ApplyT(func(v GetClusterResult) bool { return v.IsClustered }).(pulumi.BoolOutput)
}

func (o GetClusterResultOutput) Members() GetClusterMembersMapOutput {
	return o.ApplyT(func(v GetClusterResult) map[string]GetClusterMembers { return v.Members }).(GetClusterMembersMapOutput)
}

func (o GetClusterResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetClusterResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetClusterResultOutput{})
}
