// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupInstance(ctx *pulumi.Context, args *LookupInstanceArgs, opts ...pulumi.InvokeOption) (*LookupInstanceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupInstanceResult
	err = ctx.InvokePackage("incus:index/getInstance:getInstance", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInstance.
type LookupInstanceArgs struct {
	Architecture *string             `pulumi:"architecture"`
	Description  *string             `pulumi:"description"`
	Devices      []GetInstanceDevice `pulumi:"devices"`
	Ephemeral    *bool               `pulumi:"ephemeral"`
	Location     *string             `pulumi:"location"`
	Name         string              `pulumi:"name"`
	Profiles     []string            `pulumi:"profiles"`
	Project      *string             `pulumi:"project"`
	Remote       *string             `pulumi:"remote"`
	Stateful     *bool               `pulumi:"stateful"`
	Status       *string             `pulumi:"status"`
	Type         *string             `pulumi:"type"`
}

// A collection of values returned by getInstance.
type LookupInstanceResult struct {
	Architecture string              `pulumi:"architecture"`
	Config       map[string]string   `pulumi:"config"`
	Description  string              `pulumi:"description"`
	Devices      []GetInstanceDevice `pulumi:"devices"`
	Ephemeral    bool                `pulumi:"ephemeral"`
	// The provider-assigned unique ID for this managed resource.
	Id       string   `pulumi:"id"`
	Location string   `pulumi:"location"`
	Name     string   `pulumi:"name"`
	Profiles []string `pulumi:"profiles"`
	Project  *string  `pulumi:"project"`
	Remote   *string  `pulumi:"remote"`
	Stateful bool     `pulumi:"stateful"`
	Status   string   `pulumi:"status"`
	Type     string   `pulumi:"type"`
}

func LookupInstanceOutput(ctx *pulumi.Context, args LookupInstanceOutputArgs, opts ...pulumi.InvokeOption) LookupInstanceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupInstanceResultOutput, error) {
			args := v.(LookupInstanceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupInstanceResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getInstance:getInstance", args, LookupInstanceResultOutput{}, options).(LookupInstanceResultOutput), nil
		}).(LookupInstanceResultOutput)
}

// A collection of arguments for invoking getInstance.
type LookupInstanceOutputArgs struct {
	Architecture pulumi.StringPtrInput       `pulumi:"architecture"`
	Description  pulumi.StringPtrInput       `pulumi:"description"`
	Devices      GetInstanceDeviceArrayInput `pulumi:"devices"`
	Ephemeral    pulumi.BoolPtrInput         `pulumi:"ephemeral"`
	Location     pulumi.StringPtrInput       `pulumi:"location"`
	Name         pulumi.StringInput          `pulumi:"name"`
	Profiles     pulumi.StringArrayInput     `pulumi:"profiles"`
	Project      pulumi.StringPtrInput       `pulumi:"project"`
	Remote       pulumi.StringPtrInput       `pulumi:"remote"`
	Stateful     pulumi.BoolPtrInput         `pulumi:"stateful"`
	Status       pulumi.StringPtrInput       `pulumi:"status"`
	Type         pulumi.StringPtrInput       `pulumi:"type"`
}

func (LookupInstanceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInstanceArgs)(nil)).Elem()
}

// A collection of values returned by getInstance.
type LookupInstanceResultOutput struct{ *pulumi.OutputState }

func (LookupInstanceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupInstanceResult)(nil)).Elem()
}

func (o LookupInstanceResultOutput) ToLookupInstanceResultOutput() LookupInstanceResultOutput {
	return o
}

func (o LookupInstanceResultOutput) ToLookupInstanceResultOutputWithContext(ctx context.Context) LookupInstanceResultOutput {
	return o
}

func (o LookupInstanceResultOutput) Architecture() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Architecture }).(pulumi.StringOutput)
}

func (o LookupInstanceResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupInstanceResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupInstanceResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupInstanceResultOutput) Devices() GetInstanceDeviceArrayOutput {
	return o.ApplyT(func(v LookupInstanceResult) []GetInstanceDevice { return v.Devices }).(GetInstanceDeviceArrayOutput)
}

func (o LookupInstanceResultOutput) Ephemeral() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupInstanceResult) bool { return v.Ephemeral }).(pulumi.BoolOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupInstanceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupInstanceResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o LookupInstanceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupInstanceResultOutput) Profiles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupInstanceResult) []string { return v.Profiles }).(pulumi.StringArrayOutput)
}

func (o LookupInstanceResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInstanceResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupInstanceResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupInstanceResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o LookupInstanceResultOutput) Stateful() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupInstanceResult) bool { return v.Stateful }).(pulumi.BoolOutput)
}

func (o LookupInstanceResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupInstanceResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupInstanceResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupInstanceResultOutput{})
}
