// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupImage(ctx *pulumi.Context, args *LookupImageArgs, opts ...pulumi.InvokeOption) (*LookupImageResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupImageResult
	err = ctx.InvokePackage("incus:index/getImage:getImage", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getImage.
type LookupImageArgs struct {
	Architecture *string `pulumi:"architecture"`
	Fingerprint  *string `pulumi:"fingerprint"`
	Name         *string `pulumi:"name"`
	Project      *string `pulumi:"project"`
	Remote       *string `pulumi:"remote"`
	Type         *string `pulumi:"type"`
}

// A collection of values returned by getImage.
type LookupImageResult struct {
	Aliases      []string `pulumi:"aliases"`
	Architecture string   `pulumi:"architecture"`
	CreatedAt    float64  `pulumi:"createdAt"`
	Fingerprint  string   `pulumi:"fingerprint"`
	// The provider-assigned unique ID for this managed resource.
	Id      string  `pulumi:"id"`
	Name    *string `pulumi:"name"`
	Project *string `pulumi:"project"`
	Remote  *string `pulumi:"remote"`
	Type    string  `pulumi:"type"`
}

func LookupImageOutput(ctx *pulumi.Context, args LookupImageOutputArgs, opts ...pulumi.InvokeOption) LookupImageResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupImageResultOutput, error) {
			args := v.(LookupImageArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupImageResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getImage:getImage", args, LookupImageResultOutput{}, options).(LookupImageResultOutput), nil
		}).(LookupImageResultOutput)
}

// A collection of arguments for invoking getImage.
type LookupImageOutputArgs struct {
	Architecture pulumi.StringPtrInput `pulumi:"architecture"`
	Fingerprint  pulumi.StringPtrInput `pulumi:"fingerprint"`
	Name         pulumi.StringPtrInput `pulumi:"name"`
	Project      pulumi.StringPtrInput `pulumi:"project"`
	Remote       pulumi.StringPtrInput `pulumi:"remote"`
	Type         pulumi.StringPtrInput `pulumi:"type"`
}

func (LookupImageOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupImageArgs)(nil)).Elem()
}

// A collection of values returned by getImage.
type LookupImageResultOutput struct{ *pulumi.OutputState }

func (LookupImageResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupImageResult)(nil)).Elem()
}

func (o LookupImageResultOutput) ToLookupImageResultOutput() LookupImageResultOutput {
	return o
}

func (o LookupImageResultOutput) ToLookupImageResultOutputWithContext(ctx context.Context) LookupImageResultOutput {
	return o
}

func (o LookupImageResultOutput) Aliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupImageResult) []string { return v.Aliases }).(pulumi.StringArrayOutput)
}

func (o LookupImageResultOutput) Architecture() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageResult) string { return v.Architecture }).(pulumi.StringOutput)
}

func (o LookupImageResultOutput) CreatedAt() pulumi.Float64Output {
	return o.ApplyT(func(v LookupImageResult) float64 { return v.CreatedAt }).(pulumi.Float64Output)
}

func (o LookupImageResultOutput) Fingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageResult) string { return v.Fingerprint }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupImageResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupImageResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupImageResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o LookupImageResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupImageResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupImageResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupImageResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o LookupImageResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupImageResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupImageResultOutput{})
}
