// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetNetworkLoadBalancer(ctx *pulumi.Context, args *GetNetworkLoadBalancerArgs, opts ...pulumi.InvokeOption) (*GetNetworkLoadBalancerResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv GetNetworkLoadBalancerResult
	err = ctx.InvokePackage("incus:index/getNetworkLoadBalancer:getNetworkLoadBalancer", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkLoadBalancer.
type GetNetworkLoadBalancerArgs struct {
	Backends      []GetNetworkLoadBalancerBackend `pulumi:"backends"`
	Description   *string                         `pulumi:"description"`
	ListenAddress string                          `pulumi:"listenAddress"`
	Location      *string                         `pulumi:"location"`
	Network       string                          `pulumi:"network"`
	Ports         []GetNetworkLoadBalancerPort    `pulumi:"ports"`
	Project       *string                         `pulumi:"project"`
	Remote        *string                         `pulumi:"remote"`
}

// A collection of values returned by getNetworkLoadBalancer.
type GetNetworkLoadBalancerResult struct {
	Backends    []GetNetworkLoadBalancerBackend `pulumi:"backends"`
	Config      map[string]string               `pulumi:"config"`
	Description string                          `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id            string                       `pulumi:"id"`
	ListenAddress string                       `pulumi:"listenAddress"`
	Location      string                       `pulumi:"location"`
	Network       string                       `pulumi:"network"`
	Ports         []GetNetworkLoadBalancerPort `pulumi:"ports"`
	Project       *string                      `pulumi:"project"`
	Remote        *string                      `pulumi:"remote"`
}

func GetNetworkLoadBalancerOutput(ctx *pulumi.Context, args GetNetworkLoadBalancerOutputArgs, opts ...pulumi.InvokeOption) GetNetworkLoadBalancerResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetNetworkLoadBalancerResultOutput, error) {
			args := v.(GetNetworkLoadBalancerArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return GetNetworkLoadBalancerResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getNetworkLoadBalancer:getNetworkLoadBalancer", args, GetNetworkLoadBalancerResultOutput{}, options).(GetNetworkLoadBalancerResultOutput), nil
		}).(GetNetworkLoadBalancerResultOutput)
}

// A collection of arguments for invoking getNetworkLoadBalancer.
type GetNetworkLoadBalancerOutputArgs struct {
	Backends      GetNetworkLoadBalancerBackendArrayInput `pulumi:"backends"`
	Description   pulumi.StringPtrInput                   `pulumi:"description"`
	ListenAddress pulumi.StringInput                      `pulumi:"listenAddress"`
	Location      pulumi.StringPtrInput                   `pulumi:"location"`
	Network       pulumi.StringInput                      `pulumi:"network"`
	Ports         GetNetworkLoadBalancerPortArrayInput    `pulumi:"ports"`
	Project       pulumi.StringPtrInput                   `pulumi:"project"`
	Remote        pulumi.StringPtrInput                   `pulumi:"remote"`
}

func (GetNetworkLoadBalancerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetworkLoadBalancerArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkLoadBalancer.
type GetNetworkLoadBalancerResultOutput struct{ *pulumi.OutputState }

func (GetNetworkLoadBalancerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetNetworkLoadBalancerResult)(nil)).Elem()
}

func (o GetNetworkLoadBalancerResultOutput) ToGetNetworkLoadBalancerResultOutput() GetNetworkLoadBalancerResultOutput {
	return o
}

func (o GetNetworkLoadBalancerResultOutput) ToGetNetworkLoadBalancerResultOutputWithContext(ctx context.Context) GetNetworkLoadBalancerResultOutput {
	return o
}

func (o GetNetworkLoadBalancerResultOutput) Backends() GetNetworkLoadBalancerBackendArrayOutput {
	return o.ApplyT(func(v GetNetworkLoadBalancerResult) []GetNetworkLoadBalancerBackend { return v.Backends }).(GetNetworkLoadBalancerBackendArrayOutput)
}

func (o GetNetworkLoadBalancerResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetNetworkLoadBalancerResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o GetNetworkLoadBalancerResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkLoadBalancerResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetNetworkLoadBalancerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkLoadBalancerResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetNetworkLoadBalancerResultOutput) ListenAddress() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkLoadBalancerResult) string { return v.ListenAddress }).(pulumi.StringOutput)
}

func (o GetNetworkLoadBalancerResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkLoadBalancerResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o GetNetworkLoadBalancerResultOutput) Network() pulumi.StringOutput {
	return o.ApplyT(func(v GetNetworkLoadBalancerResult) string { return v.Network }).(pulumi.StringOutput)
}

func (o GetNetworkLoadBalancerResultOutput) Ports() GetNetworkLoadBalancerPortArrayOutput {
	return o.ApplyT(func(v GetNetworkLoadBalancerResult) []GetNetworkLoadBalancerPort { return v.Ports }).(GetNetworkLoadBalancerPortArrayOutput)
}

func (o GetNetworkLoadBalancerResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetNetworkLoadBalancerResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o GetNetworkLoadBalancerResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetNetworkLoadBalancerResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetNetworkLoadBalancerResultOutput{})
}
