// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetworkIntegration(ctx *pulumi.Context, args *LookupNetworkIntegrationArgs, opts ...pulumi.InvokeOption) (*LookupNetworkIntegrationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNetworkIntegrationResult
	err = ctx.InvokePackage("incus:index/getNetworkIntegration:getNetworkIntegration", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkIntegration.
type LookupNetworkIntegrationArgs struct {
	Description *string `pulumi:"description"`
	Name        string  `pulumi:"name"`
	Remote      *string `pulumi:"remote"`
	Type        *string `pulumi:"type"`
}

// A collection of values returned by getNetworkIntegration.
type LookupNetworkIntegrationResult struct {
	Config      map[string]string `pulumi:"config"`
	Description string            `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id     string  `pulumi:"id"`
	Name   string  `pulumi:"name"`
	Remote *string `pulumi:"remote"`
	Type   string  `pulumi:"type"`
}

func LookupNetworkIntegrationOutput(ctx *pulumi.Context, args LookupNetworkIntegrationOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkIntegrationResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetworkIntegrationResultOutput, error) {
			args := v.(LookupNetworkIntegrationArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupNetworkIntegrationResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getNetworkIntegration:getNetworkIntegration", args, LookupNetworkIntegrationResultOutput{}, options).(LookupNetworkIntegrationResultOutput), nil
		}).(LookupNetworkIntegrationResultOutput)
}

// A collection of arguments for invoking getNetworkIntegration.
type LookupNetworkIntegrationOutputArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	Name        pulumi.StringInput    `pulumi:"name"`
	Remote      pulumi.StringPtrInput `pulumi:"remote"`
	Type        pulumi.StringPtrInput `pulumi:"type"`
}

func (LookupNetworkIntegrationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkIntegrationArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkIntegration.
type LookupNetworkIntegrationResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkIntegrationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkIntegrationResult)(nil)).Elem()
}

func (o LookupNetworkIntegrationResultOutput) ToLookupNetworkIntegrationResultOutput() LookupNetworkIntegrationResultOutput {
	return o
}

func (o LookupNetworkIntegrationResultOutput) ToLookupNetworkIntegrationResultOutputWithContext(ctx context.Context) LookupNetworkIntegrationResultOutput {
	return o
}

func (o LookupNetworkIntegrationResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupNetworkIntegrationResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupNetworkIntegrationResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkIntegrationResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNetworkIntegrationResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkIntegrationResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetworkIntegrationResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkIntegrationResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNetworkIntegrationResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkIntegrationResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o LookupNetworkIntegrationResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkIntegrationResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkIntegrationResultOutput{})
}
