// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetworkAcl(ctx *pulumi.Context, args *LookupNetworkAclArgs, opts ...pulumi.InvokeOption) (*LookupNetworkAclResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNetworkAclResult
	err = ctx.InvokePackage("incus:index/getNetworkAcl:getNetworkAcl", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkAcl.
type LookupNetworkAclArgs struct {
	Description *string                `pulumi:"description"`
	Egresses    []GetNetworkAclEgress  `pulumi:"egresses"`
	Ingresses   []GetNetworkAclIngress `pulumi:"ingresses"`
	Name        string                 `pulumi:"name"`
	Project     *string                `pulumi:"project"`
	Remote      *string                `pulumi:"remote"`
}

// A collection of values returned by getNetworkAcl.
type LookupNetworkAclResult struct {
	Config      map[string]string     `pulumi:"config"`
	Description string                `pulumi:"description"`
	Egresses    []GetNetworkAclEgress `pulumi:"egresses"`
	// The provider-assigned unique ID for this managed resource.
	Id        string                 `pulumi:"id"`
	Ingresses []GetNetworkAclIngress `pulumi:"ingresses"`
	Name      string                 `pulumi:"name"`
	Project   *string                `pulumi:"project"`
	Remote    *string                `pulumi:"remote"`
}

func LookupNetworkAclOutput(ctx *pulumi.Context, args LookupNetworkAclOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkAclResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetworkAclResultOutput, error) {
			args := v.(LookupNetworkAclArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupNetworkAclResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getNetworkAcl:getNetworkAcl", args, LookupNetworkAclResultOutput{}, options).(LookupNetworkAclResultOutput), nil
		}).(LookupNetworkAclResultOutput)
}

// A collection of arguments for invoking getNetworkAcl.
type LookupNetworkAclOutputArgs struct {
	Description pulumi.StringPtrInput          `pulumi:"description"`
	Egresses    GetNetworkAclEgressArrayInput  `pulumi:"egresses"`
	Ingresses   GetNetworkAclIngressArrayInput `pulumi:"ingresses"`
	Name        pulumi.StringInput             `pulumi:"name"`
	Project     pulumi.StringPtrInput          `pulumi:"project"`
	Remote      pulumi.StringPtrInput          `pulumi:"remote"`
}

func (LookupNetworkAclOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkAclArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkAcl.
type LookupNetworkAclResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkAclResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkAclResult)(nil)).Elem()
}

func (o LookupNetworkAclResultOutput) ToLookupNetworkAclResultOutput() LookupNetworkAclResultOutput {
	return o
}

func (o LookupNetworkAclResultOutput) ToLookupNetworkAclResultOutputWithContext(ctx context.Context) LookupNetworkAclResultOutput {
	return o
}

func (o LookupNetworkAclResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupNetworkAclResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupNetworkAclResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkAclResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupNetworkAclResultOutput) Egresses() GetNetworkAclEgressArrayOutput {
	return o.ApplyT(func(v LookupNetworkAclResult) []GetNetworkAclEgress { return v.Egresses }).(GetNetworkAclEgressArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNetworkAclResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkAclResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetworkAclResultOutput) Ingresses() GetNetworkAclIngressArrayOutput {
	return o.ApplyT(func(v LookupNetworkAclResult) []GetNetworkAclIngress { return v.Ingresses }).(GetNetworkAclIngressArrayOutput)
}

func (o LookupNetworkAclResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkAclResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNetworkAclResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkAclResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupNetworkAclResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkAclResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkAclResultOutput{})
}
