// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetworkAddressSet(ctx *pulumi.Context, args *LookupNetworkAddressSetArgs, opts ...pulumi.InvokeOption) (*LookupNetworkAddressSetResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNetworkAddressSetResult
	err = ctx.InvokePackage("incus:index/getNetworkAddressSet:getNetworkAddressSet", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkAddressSet.
type LookupNetworkAddressSetArgs struct {
	Addresses   []string `pulumi:"addresses"`
	Description *string  `pulumi:"description"`
	Name        string   `pulumi:"name"`
	Project     *string  `pulumi:"project"`
	Remote      *string  `pulumi:"remote"`
}

// A collection of values returned by getNetworkAddressSet.
type LookupNetworkAddressSetResult struct {
	Addresses   []string          `pulumi:"addresses"`
	Config      map[string]string `pulumi:"config"`
	Description string            `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id      string  `pulumi:"id"`
	Name    string  `pulumi:"name"`
	Project *string `pulumi:"project"`
	Remote  *string `pulumi:"remote"`
}

func LookupNetworkAddressSetOutput(ctx *pulumi.Context, args LookupNetworkAddressSetOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkAddressSetResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetworkAddressSetResultOutput, error) {
			args := v.(LookupNetworkAddressSetArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupNetworkAddressSetResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getNetworkAddressSet:getNetworkAddressSet", args, LookupNetworkAddressSetResultOutput{}, options).(LookupNetworkAddressSetResultOutput), nil
		}).(LookupNetworkAddressSetResultOutput)
}

// A collection of arguments for invoking getNetworkAddressSet.
type LookupNetworkAddressSetOutputArgs struct {
	Addresses   pulumi.StringArrayInput `pulumi:"addresses"`
	Description pulumi.StringPtrInput   `pulumi:"description"`
	Name        pulumi.StringInput      `pulumi:"name"`
	Project     pulumi.StringPtrInput   `pulumi:"project"`
	Remote      pulumi.StringPtrInput   `pulumi:"remote"`
}

func (LookupNetworkAddressSetOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkAddressSetArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkAddressSet.
type LookupNetworkAddressSetResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkAddressSetResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkAddressSetResult)(nil)).Elem()
}

func (o LookupNetworkAddressSetResultOutput) ToLookupNetworkAddressSetResultOutput() LookupNetworkAddressSetResultOutput {
	return o
}

func (o LookupNetworkAddressSetResultOutput) ToLookupNetworkAddressSetResultOutputWithContext(ctx context.Context) LookupNetworkAddressSetResultOutput {
	return o
}

func (o LookupNetworkAddressSetResultOutput) Addresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetworkAddressSetResult) []string { return v.Addresses }).(pulumi.StringArrayOutput)
}

func (o LookupNetworkAddressSetResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupNetworkAddressSetResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupNetworkAddressSetResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkAddressSetResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNetworkAddressSetResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkAddressSetResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetworkAddressSetResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkAddressSetResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNetworkAddressSetResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkAddressSetResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupNetworkAddressSetResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkAddressSetResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkAddressSetResultOutput{})
}
