// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetwork(ctx *pulumi.Context, args *LookupNetworkArgs, opts ...pulumi.InvokeOption) (*LookupNetworkResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNetworkResult
	err = ctx.InvokePackage("incus:index/getNetwork:getNetwork", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetwork.
type LookupNetworkArgs struct {
	Description *string  `pulumi:"description"`
	Locations   []string `pulumi:"locations"`
	Managed     *bool    `pulumi:"managed"`
	Name        string   `pulumi:"name"`
	Project     *string  `pulumi:"project"`
	Remote      *string  `pulumi:"remote"`
	Status      *string  `pulumi:"status"`
	Target      *string  `pulumi:"target"`
	Type        *string  `pulumi:"type"`
}

// A collection of values returned by getNetwork.
type LookupNetworkResult struct {
	Config      map[string]string `pulumi:"config"`
	Description string            `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id        string   `pulumi:"id"`
	Locations []string `pulumi:"locations"`
	Managed   bool     `pulumi:"managed"`
	Name      string   `pulumi:"name"`
	Project   *string  `pulumi:"project"`
	Remote    *string  `pulumi:"remote"`
	Status    string   `pulumi:"status"`
	Target    *string  `pulumi:"target"`
	Type      string   `pulumi:"type"`
}

func LookupNetworkOutput(ctx *pulumi.Context, args LookupNetworkOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetworkResultOutput, error) {
			args := v.(LookupNetworkArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupNetworkResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getNetwork:getNetwork", args, LookupNetworkResultOutput{}, options).(LookupNetworkResultOutput), nil
		}).(LookupNetworkResultOutput)
}

// A collection of arguments for invoking getNetwork.
type LookupNetworkOutputArgs struct {
	Description pulumi.StringPtrInput   `pulumi:"description"`
	Locations   pulumi.StringArrayInput `pulumi:"locations"`
	Managed     pulumi.BoolPtrInput     `pulumi:"managed"`
	Name        pulumi.StringInput      `pulumi:"name"`
	Project     pulumi.StringPtrInput   `pulumi:"project"`
	Remote      pulumi.StringPtrInput   `pulumi:"remote"`
	Status      pulumi.StringPtrInput   `pulumi:"status"`
	Target      pulumi.StringPtrInput   `pulumi:"target"`
	Type        pulumi.StringPtrInput   `pulumi:"type"`
}

func (LookupNetworkOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkArgs)(nil)).Elem()
}

// A collection of values returned by getNetwork.
type LookupNetworkResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkResult)(nil)).Elem()
}

func (o LookupNetworkResultOutput) ToLookupNetworkResultOutput() LookupNetworkResultOutput {
	return o
}

func (o LookupNetworkResultOutput) ToLookupNetworkResultOutputWithContext(ctx context.Context) LookupNetworkResultOutput {
	return o
}

func (o LookupNetworkResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupNetworkResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupNetworkResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNetworkResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Locations() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupNetworkResult) []string { return v.Locations }).(pulumi.StringArrayOutput)
}

func (o LookupNetworkResultOutput) Managed() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupNetworkResult) bool { return v.Managed }).(pulumi.BoolOutput)
}

func (o LookupNetworkResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupNetworkResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o LookupNetworkResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupNetworkResultOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkResult) *string { return v.Target }).(pulumi.StringPtrOutput)
}

func (o LookupNetworkResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkResultOutput{})
}
