// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetworkForward(ctx *pulumi.Context, args *LookupNetworkForwardArgs, opts ...pulumi.InvokeOption) (*LookupNetworkForwardResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNetworkForwardResult
	err = ctx.InvokePackage("incus:index/getNetworkForward:getNetworkForward", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkForward.
type LookupNetworkForwardArgs struct {
	Description   *string                 `pulumi:"description"`
	ListenAddress string                  `pulumi:"listenAddress"`
	Location      *string                 `pulumi:"location"`
	Network       string                  `pulumi:"network"`
	Ports         []GetNetworkForwardPort `pulumi:"ports"`
	Project       *string                 `pulumi:"project"`
	Remote        *string                 `pulumi:"remote"`
	Target        *string                 `pulumi:"target"`
}

// A collection of values returned by getNetworkForward.
type LookupNetworkForwardResult struct {
	Config      map[string]string `pulumi:"config"`
	Description string            `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id            string                  `pulumi:"id"`
	ListenAddress string                  `pulumi:"listenAddress"`
	Location      string                  `pulumi:"location"`
	Network       string                  `pulumi:"network"`
	Ports         []GetNetworkForwardPort `pulumi:"ports"`
	Project       *string                 `pulumi:"project"`
	Remote        *string                 `pulumi:"remote"`
	Target        *string                 `pulumi:"target"`
}

func LookupNetworkForwardOutput(ctx *pulumi.Context, args LookupNetworkForwardOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkForwardResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetworkForwardResultOutput, error) {
			args := v.(LookupNetworkForwardArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupNetworkForwardResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getNetworkForward:getNetworkForward", args, LookupNetworkForwardResultOutput{}, options).(LookupNetworkForwardResultOutput), nil
		}).(LookupNetworkForwardResultOutput)
}

// A collection of arguments for invoking getNetworkForward.
type LookupNetworkForwardOutputArgs struct {
	Description   pulumi.StringPtrInput           `pulumi:"description"`
	ListenAddress pulumi.StringInput              `pulumi:"listenAddress"`
	Location      pulumi.StringPtrInput           `pulumi:"location"`
	Network       pulumi.StringInput              `pulumi:"network"`
	Ports         GetNetworkForwardPortArrayInput `pulumi:"ports"`
	Project       pulumi.StringPtrInput           `pulumi:"project"`
	Remote        pulumi.StringPtrInput           `pulumi:"remote"`
	Target        pulumi.StringPtrInput           `pulumi:"target"`
}

func (LookupNetworkForwardOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkForwardArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkForward.
type LookupNetworkForwardResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkForwardResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkForwardResult)(nil)).Elem()
}

func (o LookupNetworkForwardResultOutput) ToLookupNetworkForwardResultOutput() LookupNetworkForwardResultOutput {
	return o
}

func (o LookupNetworkForwardResultOutput) ToLookupNetworkForwardResultOutputWithContext(ctx context.Context) LookupNetworkForwardResultOutput {
	return o
}

func (o LookupNetworkForwardResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupNetworkForwardResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupNetworkForwardResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkForwardResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNetworkForwardResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkForwardResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetworkForwardResultOutput) ListenAddress() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkForwardResult) string { return v.ListenAddress }).(pulumi.StringOutput)
}

func (o LookupNetworkForwardResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkForwardResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o LookupNetworkForwardResultOutput) Network() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkForwardResult) string { return v.Network }).(pulumi.StringOutput)
}

func (o LookupNetworkForwardResultOutput) Ports() GetNetworkForwardPortArrayOutput {
	return o.ApplyT(func(v LookupNetworkForwardResult) []GetNetworkForwardPort { return v.Ports }).(GetNetworkForwardPortArrayOutput)
}

func (o LookupNetworkForwardResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkForwardResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupNetworkForwardResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkForwardResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o LookupNetworkForwardResultOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkForwardResult) *string { return v.Target }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkForwardResultOutput{})
}
