// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetworkZone(ctx *pulumi.Context, args *LookupNetworkZoneArgs, opts ...pulumi.InvokeOption) (*LookupNetworkZoneResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNetworkZoneResult
	err = ctx.InvokePackage("incus:index/getNetworkZone:getNetworkZone", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkZone.
type LookupNetworkZoneArgs struct {
	Description *string `pulumi:"description"`
	Name        string  `pulumi:"name"`
	Project     *string `pulumi:"project"`
	Remote      *string `pulumi:"remote"`
}

// A collection of values returned by getNetworkZone.
type LookupNetworkZoneResult struct {
	Config      map[string]string `pulumi:"config"`
	Description string            `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id      string  `pulumi:"id"`
	Name    string  `pulumi:"name"`
	Project *string `pulumi:"project"`
	Remote  *string `pulumi:"remote"`
}

func LookupNetworkZoneOutput(ctx *pulumi.Context, args LookupNetworkZoneOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkZoneResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetworkZoneResultOutput, error) {
			args := v.(LookupNetworkZoneArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupNetworkZoneResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getNetworkZone:getNetworkZone", args, LookupNetworkZoneResultOutput{}, options).(LookupNetworkZoneResultOutput), nil
		}).(LookupNetworkZoneResultOutput)
}

// A collection of arguments for invoking getNetworkZone.
type LookupNetworkZoneOutputArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	Name        pulumi.StringInput    `pulumi:"name"`
	Project     pulumi.StringPtrInput `pulumi:"project"`
	Remote      pulumi.StringPtrInput `pulumi:"remote"`
}

func (LookupNetworkZoneOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkZoneArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkZone.
type LookupNetworkZoneResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkZoneResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkZoneResult)(nil)).Elem()
}

func (o LookupNetworkZoneResultOutput) ToLookupNetworkZoneResultOutput() LookupNetworkZoneResultOutput {
	return o
}

func (o LookupNetworkZoneResultOutput) ToLookupNetworkZoneResultOutputWithContext(ctx context.Context) LookupNetworkZoneResultOutput {
	return o
}

func (o LookupNetworkZoneResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupNetworkZoneResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupNetworkZoneResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkZoneResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNetworkZoneResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkZoneResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetworkZoneResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkZoneResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNetworkZoneResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkZoneResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupNetworkZoneResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkZoneResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkZoneResultOutput{})
}
