// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupNetworkPeer(ctx *pulumi.Context, args *LookupNetworkPeerArgs, opts ...pulumi.InvokeOption) (*LookupNetworkPeerResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupNetworkPeerResult
	err = ctx.InvokePackage("incus:index/getNetworkPeer:getNetworkPeer", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetworkPeer.
type LookupNetworkPeerArgs struct {
	Description       *string `pulumi:"description"`
	Name              string  `pulumi:"name"`
	Network           string  `pulumi:"network"`
	Project           *string `pulumi:"project"`
	Remote            *string `pulumi:"remote"`
	Status            *string `pulumi:"status"`
	TargetIntegration *string `pulumi:"targetIntegration"`
	TargetNetwork     *string `pulumi:"targetNetwork"`
	TargetProject     *string `pulumi:"targetProject"`
	Type              *string `pulumi:"type"`
}

// A collection of values returned by getNetworkPeer.
type LookupNetworkPeerResult struct {
	Config      map[string]string `pulumi:"config"`
	Description string            `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id                string  `pulumi:"id"`
	Name              string  `pulumi:"name"`
	Network           string  `pulumi:"network"`
	Project           *string `pulumi:"project"`
	Remote            *string `pulumi:"remote"`
	Status            string  `pulumi:"status"`
	TargetIntegration string  `pulumi:"targetIntegration"`
	TargetNetwork     string  `pulumi:"targetNetwork"`
	TargetProject     string  `pulumi:"targetProject"`
	Type              string  `pulumi:"type"`
}

func LookupNetworkPeerOutput(ctx *pulumi.Context, args LookupNetworkPeerOutputArgs, opts ...pulumi.InvokeOption) LookupNetworkPeerResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupNetworkPeerResultOutput, error) {
			args := v.(LookupNetworkPeerArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupNetworkPeerResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getNetworkPeer:getNetworkPeer", args, LookupNetworkPeerResultOutput{}, options).(LookupNetworkPeerResultOutput), nil
		}).(LookupNetworkPeerResultOutput)
}

// A collection of arguments for invoking getNetworkPeer.
type LookupNetworkPeerOutputArgs struct {
	Description       pulumi.StringPtrInput `pulumi:"description"`
	Name              pulumi.StringInput    `pulumi:"name"`
	Network           pulumi.StringInput    `pulumi:"network"`
	Project           pulumi.StringPtrInput `pulumi:"project"`
	Remote            pulumi.StringPtrInput `pulumi:"remote"`
	Status            pulumi.StringPtrInput `pulumi:"status"`
	TargetIntegration pulumi.StringPtrInput `pulumi:"targetIntegration"`
	TargetNetwork     pulumi.StringPtrInput `pulumi:"targetNetwork"`
	TargetProject     pulumi.StringPtrInput `pulumi:"targetProject"`
	Type              pulumi.StringPtrInput `pulumi:"type"`
}

func (LookupNetworkPeerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkPeerArgs)(nil)).Elem()
}

// A collection of values returned by getNetworkPeer.
type LookupNetworkPeerResultOutput struct{ *pulumi.OutputState }

func (LookupNetworkPeerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetworkPeerResult)(nil)).Elem()
}

func (o LookupNetworkPeerResultOutput) ToLookupNetworkPeerResultOutput() LookupNetworkPeerResultOutput {
	return o
}

func (o LookupNetworkPeerResultOutput) ToLookupNetworkPeerResultOutputWithContext(ctx context.Context) LookupNetworkPeerResultOutput {
	return o
}

func (o LookupNetworkPeerResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupNetworkPeerResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNetworkPeerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetworkPeerResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupNetworkPeerResultOutput) Network() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) string { return v.Network }).(pulumi.StringOutput)
}

func (o LookupNetworkPeerResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupNetworkPeerResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o LookupNetworkPeerResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupNetworkPeerResultOutput) TargetIntegration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) string { return v.TargetIntegration }).(pulumi.StringOutput)
}

func (o LookupNetworkPeerResultOutput) TargetNetwork() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) string { return v.TargetNetwork }).(pulumi.StringOutput)
}

func (o LookupNetworkPeerResultOutput) TargetProject() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) string { return v.TargetProject }).(pulumi.StringOutput)
}

func (o LookupNetworkPeerResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetworkPeerResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetworkPeerResultOutput{})
}
