// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupProfile(ctx *pulumi.Context, args *LookupProfileArgs, opts ...pulumi.InvokeOption) (*LookupProfileResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupProfileResult
	err = ctx.InvokePackage("incus:index/getProfile:getProfile", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getProfile.
type LookupProfileArgs struct {
	Description *string            `pulumi:"description"`
	Devices     []GetProfileDevice `pulumi:"devices"`
	Name        string             `pulumi:"name"`
	Project     *string            `pulumi:"project"`
	Remote      *string            `pulumi:"remote"`
}

// A collection of values returned by getProfile.
type LookupProfileResult struct {
	Config      map[string]string  `pulumi:"config"`
	Description string             `pulumi:"description"`
	Devices     []GetProfileDevice `pulumi:"devices"`
	// The provider-assigned unique ID for this managed resource.
	Id      string  `pulumi:"id"`
	Name    string  `pulumi:"name"`
	Project *string `pulumi:"project"`
	Remote  *string `pulumi:"remote"`
}

func LookupProfileOutput(ctx *pulumi.Context, args LookupProfileOutputArgs, opts ...pulumi.InvokeOption) LookupProfileResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupProfileResultOutput, error) {
			args := v.(LookupProfileArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupProfileResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getProfile:getProfile", args, LookupProfileResultOutput{}, options).(LookupProfileResultOutput), nil
		}).(LookupProfileResultOutput)
}

// A collection of arguments for invoking getProfile.
type LookupProfileOutputArgs struct {
	Description pulumi.StringPtrInput      `pulumi:"description"`
	Devices     GetProfileDeviceArrayInput `pulumi:"devices"`
	Name        pulumi.StringInput         `pulumi:"name"`
	Project     pulumi.StringPtrInput      `pulumi:"project"`
	Remote      pulumi.StringPtrInput      `pulumi:"remote"`
}

func (LookupProfileOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupProfileArgs)(nil)).Elem()
}

// A collection of values returned by getProfile.
type LookupProfileResultOutput struct{ *pulumi.OutputState }

func (LookupProfileResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupProfileResult)(nil)).Elem()
}

func (o LookupProfileResultOutput) ToLookupProfileResultOutput() LookupProfileResultOutput {
	return o
}

func (o LookupProfileResultOutput) ToLookupProfileResultOutputWithContext(ctx context.Context) LookupProfileResultOutput {
	return o
}

func (o LookupProfileResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupProfileResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupProfileResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupProfileResultOutput) Devices() GetProfileDeviceArrayOutput {
	return o.ApplyT(func(v LookupProfileResult) []GetProfileDevice { return v.Devices }).(GetProfileDeviceArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupProfileResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupProfileResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProfileResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupProfileResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupProfileResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupProfileResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupProfileResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupProfileResultOutput{})
}
