// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupStorageBucket(ctx *pulumi.Context, args *LookupStorageBucketArgs, opts ...pulumi.InvokeOption) (*LookupStorageBucketResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupStorageBucketResult
	err = ctx.InvokePackage("incus:index/getStorageBucket:getStorageBucket", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getStorageBucket.
type LookupStorageBucketArgs struct {
	Description *string `pulumi:"description"`
	Location    *string `pulumi:"location"`
	Name        string  `pulumi:"name"`
	Project     *string `pulumi:"project"`
	Remote      *string `pulumi:"remote"`
	S3Url       *string `pulumi:"s3Url"`
	StoragePool string  `pulumi:"storagePool"`
	Target      *string `pulumi:"target"`
}

// A collection of values returned by getStorageBucket.
type LookupStorageBucketResult struct {
	Config      map[string]string `pulumi:"config"`
	Description string            `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id          string  `pulumi:"id"`
	Location    string  `pulumi:"location"`
	Name        string  `pulumi:"name"`
	Project     *string `pulumi:"project"`
	Remote      *string `pulumi:"remote"`
	S3Url       string  `pulumi:"s3Url"`
	StoragePool string  `pulumi:"storagePool"`
	Target      *string `pulumi:"target"`
}

func LookupStorageBucketOutput(ctx *pulumi.Context, args LookupStorageBucketOutputArgs, opts ...pulumi.InvokeOption) LookupStorageBucketResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupStorageBucketResultOutput, error) {
			args := v.(LookupStorageBucketArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupStorageBucketResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getStorageBucket:getStorageBucket", args, LookupStorageBucketResultOutput{}, options).(LookupStorageBucketResultOutput), nil
		}).(LookupStorageBucketResultOutput)
}

// A collection of arguments for invoking getStorageBucket.
type LookupStorageBucketOutputArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	Location    pulumi.StringPtrInput `pulumi:"location"`
	Name        pulumi.StringInput    `pulumi:"name"`
	Project     pulumi.StringPtrInput `pulumi:"project"`
	Remote      pulumi.StringPtrInput `pulumi:"remote"`
	S3Url       pulumi.StringPtrInput `pulumi:"s3Url"`
	StoragePool pulumi.StringInput    `pulumi:"storagePool"`
	Target      pulumi.StringPtrInput `pulumi:"target"`
}

func (LookupStorageBucketOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupStorageBucketArgs)(nil)).Elem()
}

// A collection of values returned by getStorageBucket.
type LookupStorageBucketResultOutput struct{ *pulumi.OutputState }

func (LookupStorageBucketResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupStorageBucketResult)(nil)).Elem()
}

func (o LookupStorageBucketResultOutput) ToLookupStorageBucketResultOutput() LookupStorageBucketResultOutput {
	return o
}

func (o LookupStorageBucketResultOutput) ToLookupStorageBucketResultOutputWithContext(ctx context.Context) LookupStorageBucketResultOutput {
	return o
}

func (o LookupStorageBucketResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupStorageBucketResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupStorageBucketResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageBucketResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupStorageBucketResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageBucketResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupStorageBucketResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageBucketResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o LookupStorageBucketResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageBucketResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupStorageBucketResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupStorageBucketResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupStorageBucketResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupStorageBucketResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o LookupStorageBucketResultOutput) S3Url() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageBucketResult) string { return v.S3Url }).(pulumi.StringOutput)
}

func (o LookupStorageBucketResultOutput) StoragePool() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageBucketResult) string { return v.StoragePool }).(pulumi.StringOutput)
}

func (o LookupStorageBucketResultOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupStorageBucketResult) *string { return v.Target }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupStorageBucketResultOutput{})
}
