// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupStorageVolume(ctx *pulumi.Context, args *LookupStorageVolumeArgs, opts ...pulumi.InvokeOption) (*LookupStorageVolumeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupStorageVolumeResult
	err = ctx.InvokePackage("incus:index/getStorageVolume:getStorageVolume", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getStorageVolume.
type LookupStorageVolumeArgs struct {
	ContentType *string `pulumi:"contentType"`
	Description *string `pulumi:"description"`
	Location    *string `pulumi:"location"`
	Name        string  `pulumi:"name"`
	Project     *string `pulumi:"project"`
	Remote      *string `pulumi:"remote"`
	StoragePool string  `pulumi:"storagePool"`
	Target      *string `pulumi:"target"`
	Type        string  `pulumi:"type"`
}

// A collection of values returned by getStorageVolume.
type LookupStorageVolumeResult struct {
	Config      map[string]string `pulumi:"config"`
	ContentType string            `pulumi:"contentType"`
	Description string            `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id          string  `pulumi:"id"`
	Location    string  `pulumi:"location"`
	Name        string  `pulumi:"name"`
	Project     *string `pulumi:"project"`
	Remote      *string `pulumi:"remote"`
	StoragePool string  `pulumi:"storagePool"`
	Target      *string `pulumi:"target"`
	Type        string  `pulumi:"type"`
}

func LookupStorageVolumeOutput(ctx *pulumi.Context, args LookupStorageVolumeOutputArgs, opts ...pulumi.InvokeOption) LookupStorageVolumeResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupStorageVolumeResultOutput, error) {
			args := v.(LookupStorageVolumeArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupStorageVolumeResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getStorageVolume:getStorageVolume", args, LookupStorageVolumeResultOutput{}, options).(LookupStorageVolumeResultOutput), nil
		}).(LookupStorageVolumeResultOutput)
}

// A collection of arguments for invoking getStorageVolume.
type LookupStorageVolumeOutputArgs struct {
	ContentType pulumi.StringPtrInput `pulumi:"contentType"`
	Description pulumi.StringPtrInput `pulumi:"description"`
	Location    pulumi.StringPtrInput `pulumi:"location"`
	Name        pulumi.StringInput    `pulumi:"name"`
	Project     pulumi.StringPtrInput `pulumi:"project"`
	Remote      pulumi.StringPtrInput `pulumi:"remote"`
	StoragePool pulumi.StringInput    `pulumi:"storagePool"`
	Target      pulumi.StringPtrInput `pulumi:"target"`
	Type        pulumi.StringInput    `pulumi:"type"`
}

func (LookupStorageVolumeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupStorageVolumeArgs)(nil)).Elem()
}

// A collection of values returned by getStorageVolume.
type LookupStorageVolumeResultOutput struct{ *pulumi.OutputState }

func (LookupStorageVolumeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupStorageVolumeResult)(nil)).Elem()
}

func (o LookupStorageVolumeResultOutput) ToLookupStorageVolumeResultOutput() LookupStorageVolumeResultOutput {
	return o
}

func (o LookupStorageVolumeResultOutput) ToLookupStorageVolumeResultOutputWithContext(ctx context.Context) LookupStorageVolumeResultOutput {
	return o
}

func (o LookupStorageVolumeResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupStorageVolumeResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupStorageVolumeResultOutput) ContentType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageVolumeResult) string { return v.ContentType }).(pulumi.StringOutput)
}

func (o LookupStorageVolumeResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageVolumeResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupStorageVolumeResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageVolumeResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupStorageVolumeResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageVolumeResult) string { return v.Location }).(pulumi.StringOutput)
}

func (o LookupStorageVolumeResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageVolumeResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupStorageVolumeResultOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupStorageVolumeResult) *string { return v.Project }).(pulumi.StringPtrOutput)
}

func (o LookupStorageVolumeResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupStorageVolumeResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o LookupStorageVolumeResultOutput) StoragePool() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageVolumeResult) string { return v.StoragePool }).(pulumi.StringOutput)
}

func (o LookupStorageVolumeResultOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupStorageVolumeResult) *string { return v.Target }).(pulumi.StringPtrOutput)
}

func (o LookupStorageVolumeResultOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStorageVolumeResult) string { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupStorageVolumeResultOutput{})
}
