// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupStoragePool(ctx *pulumi.Context, args *LookupStoragePoolArgs, opts ...pulumi.InvokeOption) (*LookupStoragePoolResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var rv LookupStoragePoolResult
	err = ctx.InvokePackage("incus:index/getStoragePool:getStoragePool", args, &rv, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getStoragePool.
type LookupStoragePoolArgs struct {
	Description *string `pulumi:"description"`
	Driver      *string `pulumi:"driver"`
	Name        string  `pulumi:"name"`
	Remote      *string `pulumi:"remote"`
	Status      *string `pulumi:"status"`
	Target      *string `pulumi:"target"`
}

// A collection of values returned by getStoragePool.
type LookupStoragePoolResult struct {
	Config      map[string]string `pulumi:"config"`
	Description string            `pulumi:"description"`
	Driver      string            `pulumi:"driver"`
	// The provider-assigned unique ID for this managed resource.
	Id     string  `pulumi:"id"`
	Name   string  `pulumi:"name"`
	Remote *string `pulumi:"remote"`
	Status string  `pulumi:"status"`
	Target *string `pulumi:"target"`
}

func LookupStoragePoolOutput(ctx *pulumi.Context, args LookupStoragePoolOutputArgs, opts ...pulumi.InvokeOption) LookupStoragePoolResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupStoragePoolResultOutput, error) {
			args := v.(LookupStoragePoolArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			ref, err := internal.PkgGetPackageRef(ctx)
			if err != nil {
				return LookupStoragePoolResultOutput{}, err
			}
			options.PackageRef = ref
			return ctx.InvokeOutput("incus:index/getStoragePool:getStoragePool", args, LookupStoragePoolResultOutput{}, options).(LookupStoragePoolResultOutput), nil
		}).(LookupStoragePoolResultOutput)
}

// A collection of arguments for invoking getStoragePool.
type LookupStoragePoolOutputArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	Driver      pulumi.StringPtrInput `pulumi:"driver"`
	Name        pulumi.StringInput    `pulumi:"name"`
	Remote      pulumi.StringPtrInput `pulumi:"remote"`
	Status      pulumi.StringPtrInput `pulumi:"status"`
	Target      pulumi.StringPtrInput `pulumi:"target"`
}

func (LookupStoragePoolOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupStoragePoolArgs)(nil)).Elem()
}

// A collection of values returned by getStoragePool.
type LookupStoragePoolResultOutput struct{ *pulumi.OutputState }

func (LookupStoragePoolResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupStoragePoolResult)(nil)).Elem()
}

func (o LookupStoragePoolResultOutput) ToLookupStoragePoolResultOutput() LookupStoragePoolResultOutput {
	return o
}

func (o LookupStoragePoolResultOutput) ToLookupStoragePoolResultOutputWithContext(ctx context.Context) LookupStoragePoolResultOutput {
	return o
}

func (o LookupStoragePoolResultOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupStoragePoolResult) map[string]string { return v.Config }).(pulumi.StringMapOutput)
}

func (o LookupStoragePoolResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStoragePoolResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupStoragePoolResultOutput) Driver() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStoragePoolResult) string { return v.Driver }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupStoragePoolResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStoragePoolResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupStoragePoolResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStoragePoolResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupStoragePoolResultOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupStoragePoolResult) *string { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o LookupStoragePoolResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupStoragePoolResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupStoragePoolResultOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupStoragePoolResult) *string { return v.Target }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupStoragePoolResultOutput{})
}
