// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Image struct {
	pulumi.CustomResourceState

	// Image alias
	Aliases        ImageAliasArrayOutput        `pulumi:"aliases"`
	CopiedAliases  pulumi.StringArrayOutput     `pulumi:"copiedAliases"`
	CreatedAt      pulumi.Float64Output         `pulumi:"createdAt"`
	Fingerprint    pulumi.StringOutput          `pulumi:"fingerprint"`
	Project        pulumi.StringPtrOutput       `pulumi:"project"`
	Remote         pulumi.StringPtrOutput       `pulumi:"remote"`
	ResourceId     pulumi.StringOutput          `pulumi:"resourceId"`
	SourceFile     ImageSourceFilePtrOutput     `pulumi:"sourceFile"`
	SourceImage    ImageSourceImagePtrOutput    `pulumi:"sourceImage"`
	SourceInstance ImageSourceInstancePtrOutput `pulumi:"sourceInstance"`
}

// NewImage registers a new resource with the given unique name, arguments, and options.
func NewImage(ctx *pulumi.Context,
	name string, args *ImageArgs, opts ...pulumi.ResourceOption) (*Image, error) {
	if args == nil {
		args = &ImageArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Image
	err = ctx.RegisterPackageResource("incus:index/image:Image", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetImage gets an existing Image resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetImage(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ImageState, opts ...pulumi.ResourceOption) (*Image, error) {
	var resource Image
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/image:Image", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Image resources.
type imageState struct {
	// Image alias
	Aliases        []ImageAlias         `pulumi:"aliases"`
	CopiedAliases  []string             `pulumi:"copiedAliases"`
	CreatedAt      *float64             `pulumi:"createdAt"`
	Fingerprint    *string              `pulumi:"fingerprint"`
	Project        *string              `pulumi:"project"`
	Remote         *string              `pulumi:"remote"`
	ResourceId     *string              `pulumi:"resourceId"`
	SourceFile     *ImageSourceFile     `pulumi:"sourceFile"`
	SourceImage    *ImageSourceImage    `pulumi:"sourceImage"`
	SourceInstance *ImageSourceInstance `pulumi:"sourceInstance"`
}

type ImageState struct {
	// Image alias
	Aliases        ImageAliasArrayInput
	CopiedAliases  pulumi.StringArrayInput
	CreatedAt      pulumi.Float64PtrInput
	Fingerprint    pulumi.StringPtrInput
	Project        pulumi.StringPtrInput
	Remote         pulumi.StringPtrInput
	ResourceId     pulumi.StringPtrInput
	SourceFile     ImageSourceFilePtrInput
	SourceImage    ImageSourceImagePtrInput
	SourceInstance ImageSourceInstancePtrInput
}

func (ImageState) ElementType() reflect.Type {
	return reflect.TypeOf((*imageState)(nil)).Elem()
}

type imageArgs struct {
	// Image alias
	Aliases        []ImageAlias         `pulumi:"aliases"`
	Project        *string              `pulumi:"project"`
	Remote         *string              `pulumi:"remote"`
	SourceFile     *ImageSourceFile     `pulumi:"sourceFile"`
	SourceImage    *ImageSourceImage    `pulumi:"sourceImage"`
	SourceInstance *ImageSourceInstance `pulumi:"sourceInstance"`
}

// The set of arguments for constructing a Image resource.
type ImageArgs struct {
	// Image alias
	Aliases        ImageAliasArrayInput
	Project        pulumi.StringPtrInput
	Remote         pulumi.StringPtrInput
	SourceFile     ImageSourceFilePtrInput
	SourceImage    ImageSourceImagePtrInput
	SourceInstance ImageSourceInstancePtrInput
}

func (ImageArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*imageArgs)(nil)).Elem()
}

type ImageInput interface {
	pulumi.Input

	ToImageOutput() ImageOutput
	ToImageOutputWithContext(ctx context.Context) ImageOutput
}

func (*Image) ElementType() reflect.Type {
	return reflect.TypeOf((**Image)(nil)).Elem()
}

func (i *Image) ToImageOutput() ImageOutput {
	return i.ToImageOutputWithContext(context.Background())
}

func (i *Image) ToImageOutputWithContext(ctx context.Context) ImageOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ImageOutput)
}

type ImageOutput struct{ *pulumi.OutputState }

func (ImageOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Image)(nil)).Elem()
}

func (o ImageOutput) ToImageOutput() ImageOutput {
	return o
}

func (o ImageOutput) ToImageOutputWithContext(ctx context.Context) ImageOutput {
	return o
}

// Image alias
func (o ImageOutput) Aliases() ImageAliasArrayOutput {
	return o.ApplyT(func(v *Image) ImageAliasArrayOutput { return v.Aliases }).(ImageAliasArrayOutput)
}

func (o ImageOutput) CopiedAliases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Image) pulumi.StringArrayOutput { return v.CopiedAliases }).(pulumi.StringArrayOutput)
}

func (o ImageOutput) CreatedAt() pulumi.Float64Output {
	return o.ApplyT(func(v *Image) pulumi.Float64Output { return v.CreatedAt }).(pulumi.Float64Output)
}

func (o ImageOutput) Fingerprint() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.Fingerprint }).(pulumi.StringOutput)
}

func (o ImageOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Image) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o ImageOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Image) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o ImageOutput) ResourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *Image) pulumi.StringOutput { return v.ResourceId }).(pulumi.StringOutput)
}

func (o ImageOutput) SourceFile() ImageSourceFilePtrOutput {
	return o.ApplyT(func(v *Image) ImageSourceFilePtrOutput { return v.SourceFile }).(ImageSourceFilePtrOutput)
}

func (o ImageOutput) SourceImage() ImageSourceImagePtrOutput {
	return o.ApplyT(func(v *Image) ImageSourceImagePtrOutput { return v.SourceImage }).(ImageSourceImagePtrOutput)
}

func (o ImageOutput) SourceInstance() ImageSourceInstancePtrOutput {
	return o.ApplyT(func(v *Image) ImageSourceInstancePtrOutput { return v.SourceInstance }).(ImageSourceInstancePtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ImageInput)(nil)).Elem(), &Image{})
	pulumi.RegisterOutputType(ImageOutput{})
}
