// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Instance struct {
	pulumi.CustomResourceState

	Architecture pulumi.StringOutput    `pulumi:"architecture"`
	Config       pulumi.StringMapOutput `pulumi:"config"`
	Description  pulumi.StringOutput    `pulumi:"description"`
	// Profile device
	Devices   InstanceDeviceArrayOutput `pulumi:"devices"`
	Ephemeral pulumi.BoolOutput         `pulumi:"ephemeral"`
	// Upload file to instance
	Files          InstanceFileArrayOutput         `pulumi:"files"`
	Image          pulumi.StringPtrOutput          `pulumi:"image"`
	Ipv4Address    pulumi.StringOutput             `pulumi:"ipv4Address"`
	Ipv6Address    pulumi.StringOutput             `pulumi:"ipv6Address"`
	MacAddress     pulumi.StringOutput             `pulumi:"macAddress"`
	Name           pulumi.StringOutput             `pulumi:"name"`
	Profiles       pulumi.StringArrayOutput        `pulumi:"profiles"`
	Project        pulumi.StringPtrOutput          `pulumi:"project"`
	Remote         pulumi.StringPtrOutput          `pulumi:"remote"`
	Running        pulumi.BoolOutput               `pulumi:"running"`
	SourceFile     pulumi.StringPtrOutput          `pulumi:"sourceFile"`
	SourceInstance InstanceSourceInstancePtrOutput `pulumi:"sourceInstance"`
	Status         pulumi.StringOutput             `pulumi:"status"`
	Target         pulumi.StringOutput             `pulumi:"target"`
	Type           pulumi.StringOutput             `pulumi:"type"`
	// Wait for instance to be ready
	WaitFors InstanceWaitForArrayOutput `pulumi:"waitFors"`
}

// NewInstance registers a new resource with the given unique name, arguments, and options.
func NewInstance(ctx *pulumi.Context,
	name string, args *InstanceArgs, opts ...pulumi.ResourceOption) (*Instance, error) {
	if args == nil {
		args = &InstanceArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Instance
	err = ctx.RegisterPackageResource("incus:index/instance:Instance", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInstance gets an existing Instance resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInstance(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InstanceState, opts ...pulumi.ResourceOption) (*Instance, error) {
	var resource Instance
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/instance:Instance", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Instance resources.
type instanceState struct {
	Architecture *string           `pulumi:"architecture"`
	Config       map[string]string `pulumi:"config"`
	Description  *string           `pulumi:"description"`
	// Profile device
	Devices   []InstanceDevice `pulumi:"devices"`
	Ephemeral *bool            `pulumi:"ephemeral"`
	// Upload file to instance
	Files          []InstanceFile          `pulumi:"files"`
	Image          *string                 `pulumi:"image"`
	Ipv4Address    *string                 `pulumi:"ipv4Address"`
	Ipv6Address    *string                 `pulumi:"ipv6Address"`
	MacAddress     *string                 `pulumi:"macAddress"`
	Name           *string                 `pulumi:"name"`
	Profiles       []string                `pulumi:"profiles"`
	Project        *string                 `pulumi:"project"`
	Remote         *string                 `pulumi:"remote"`
	Running        *bool                   `pulumi:"running"`
	SourceFile     *string                 `pulumi:"sourceFile"`
	SourceInstance *InstanceSourceInstance `pulumi:"sourceInstance"`
	Status         *string                 `pulumi:"status"`
	Target         *string                 `pulumi:"target"`
	Type           *string                 `pulumi:"type"`
	// Wait for instance to be ready
	WaitFors []InstanceWaitFor `pulumi:"waitFors"`
}

type InstanceState struct {
	Architecture pulumi.StringPtrInput
	Config       pulumi.StringMapInput
	Description  pulumi.StringPtrInput
	// Profile device
	Devices   InstanceDeviceArrayInput
	Ephemeral pulumi.BoolPtrInput
	// Upload file to instance
	Files          InstanceFileArrayInput
	Image          pulumi.StringPtrInput
	Ipv4Address    pulumi.StringPtrInput
	Ipv6Address    pulumi.StringPtrInput
	MacAddress     pulumi.StringPtrInput
	Name           pulumi.StringPtrInput
	Profiles       pulumi.StringArrayInput
	Project        pulumi.StringPtrInput
	Remote         pulumi.StringPtrInput
	Running        pulumi.BoolPtrInput
	SourceFile     pulumi.StringPtrInput
	SourceInstance InstanceSourceInstancePtrInput
	Status         pulumi.StringPtrInput
	Target         pulumi.StringPtrInput
	Type           pulumi.StringPtrInput
	// Wait for instance to be ready
	WaitFors InstanceWaitForArrayInput
}

func (InstanceState) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceState)(nil)).Elem()
}

type instanceArgs struct {
	Architecture *string           `pulumi:"architecture"`
	Config       map[string]string `pulumi:"config"`
	Description  *string           `pulumi:"description"`
	// Profile device
	Devices   []InstanceDevice `pulumi:"devices"`
	Ephemeral *bool            `pulumi:"ephemeral"`
	// Upload file to instance
	Files          []InstanceFile          `pulumi:"files"`
	Image          *string                 `pulumi:"image"`
	Name           *string                 `pulumi:"name"`
	Profiles       []string                `pulumi:"profiles"`
	Project        *string                 `pulumi:"project"`
	Remote         *string                 `pulumi:"remote"`
	Running        *bool                   `pulumi:"running"`
	SourceFile     *string                 `pulumi:"sourceFile"`
	SourceInstance *InstanceSourceInstance `pulumi:"sourceInstance"`
	Target         *string                 `pulumi:"target"`
	Type           *string                 `pulumi:"type"`
	// Wait for instance to be ready
	WaitFors []InstanceWaitFor `pulumi:"waitFors"`
}

// The set of arguments for constructing a Instance resource.
type InstanceArgs struct {
	Architecture pulumi.StringPtrInput
	Config       pulumi.StringMapInput
	Description  pulumi.StringPtrInput
	// Profile device
	Devices   InstanceDeviceArrayInput
	Ephemeral pulumi.BoolPtrInput
	// Upload file to instance
	Files          InstanceFileArrayInput
	Image          pulumi.StringPtrInput
	Name           pulumi.StringPtrInput
	Profiles       pulumi.StringArrayInput
	Project        pulumi.StringPtrInput
	Remote         pulumi.StringPtrInput
	Running        pulumi.BoolPtrInput
	SourceFile     pulumi.StringPtrInput
	SourceInstance InstanceSourceInstancePtrInput
	Target         pulumi.StringPtrInput
	Type           pulumi.StringPtrInput
	// Wait for instance to be ready
	WaitFors InstanceWaitForArrayInput
}

func (InstanceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceArgs)(nil)).Elem()
}

type InstanceInput interface {
	pulumi.Input

	ToInstanceOutput() InstanceOutput
	ToInstanceOutputWithContext(ctx context.Context) InstanceOutput
}

func (*Instance) ElementType() reflect.Type {
	return reflect.TypeOf((**Instance)(nil)).Elem()
}

func (i *Instance) ToInstanceOutput() InstanceOutput {
	return i.ToInstanceOutputWithContext(context.Background())
}

func (i *Instance) ToInstanceOutputWithContext(ctx context.Context) InstanceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceOutput)
}

type InstanceOutput struct{ *pulumi.OutputState }

func (InstanceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Instance)(nil)).Elem()
}

func (o InstanceOutput) ToInstanceOutput() InstanceOutput {
	return o
}

func (o InstanceOutput) ToInstanceOutputWithContext(ctx context.Context) InstanceOutput {
	return o
}

func (o InstanceOutput) Architecture() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Architecture }).(pulumi.StringOutput)
}

func (o InstanceOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o InstanceOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Profile device
func (o InstanceOutput) Devices() InstanceDeviceArrayOutput {
	return o.ApplyT(func(v *Instance) InstanceDeviceArrayOutput { return v.Devices }).(InstanceDeviceArrayOutput)
}

func (o InstanceOutput) Ephemeral() pulumi.BoolOutput {
	return o.ApplyT(func(v *Instance) pulumi.BoolOutput { return v.Ephemeral }).(pulumi.BoolOutput)
}

// Upload file to instance
func (o InstanceOutput) Files() InstanceFileArrayOutput {
	return o.ApplyT(func(v *Instance) InstanceFileArrayOutput { return v.Files }).(InstanceFileArrayOutput)
}

func (o InstanceOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringPtrOutput { return v.Image }).(pulumi.StringPtrOutput)
}

func (o InstanceOutput) Ipv4Address() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Ipv4Address }).(pulumi.StringOutput)
}

func (o InstanceOutput) Ipv6Address() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Ipv6Address }).(pulumi.StringOutput)
}

func (o InstanceOutput) MacAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.MacAddress }).(pulumi.StringOutput)
}

func (o InstanceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o InstanceOutput) Profiles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringArrayOutput { return v.Profiles }).(pulumi.StringArrayOutput)
}

func (o InstanceOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o InstanceOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o InstanceOutput) Running() pulumi.BoolOutput {
	return o.ApplyT(func(v *Instance) pulumi.BoolOutput { return v.Running }).(pulumi.BoolOutput)
}

func (o InstanceOutput) SourceFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringPtrOutput { return v.SourceFile }).(pulumi.StringPtrOutput)
}

func (o InstanceOutput) SourceInstance() InstanceSourceInstancePtrOutput {
	return o.ApplyT(func(v *Instance) InstanceSourceInstancePtrOutput { return v.SourceInstance }).(InstanceSourceInstancePtrOutput)
}

func (o InstanceOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o InstanceOutput) Target() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Target }).(pulumi.StringOutput)
}

func (o InstanceOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *Instance) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

// Wait for instance to be ready
func (o InstanceOutput) WaitFors() InstanceWaitForArrayOutput {
	return o.ApplyT(func(v *Instance) InstanceWaitForArrayOutput { return v.WaitFors }).(InstanceWaitForArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceInput)(nil)).Elem(), &Instance{})
	pulumi.RegisterOutputType(InstanceOutput{})
}
