// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type InstanceSnapshot struct {
	pulumi.CustomResourceState

	CreatedAt pulumi.Float64Output   `pulumi:"createdAt"`
	Instance  pulumi.StringOutput    `pulumi:"instance"`
	Name      pulumi.StringOutput    `pulumi:"name"`
	Project   pulumi.StringPtrOutput `pulumi:"project"`
	Remote    pulumi.StringPtrOutput `pulumi:"remote"`
	Stateful  pulumi.BoolOutput      `pulumi:"stateful"`
}

// NewInstanceSnapshot registers a new resource with the given unique name, arguments, and options.
func NewInstanceSnapshot(ctx *pulumi.Context,
	name string, args *InstanceSnapshotArgs, opts ...pulumi.ResourceOption) (*InstanceSnapshot, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Instance == nil {
		return nil, errors.New("invalid value for required argument 'Instance'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource InstanceSnapshot
	err = ctx.RegisterPackageResource("incus:index/instanceSnapshot:InstanceSnapshot", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInstanceSnapshot gets an existing InstanceSnapshot resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInstanceSnapshot(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InstanceSnapshotState, opts ...pulumi.ResourceOption) (*InstanceSnapshot, error) {
	var resource InstanceSnapshot
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/instanceSnapshot:InstanceSnapshot", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering InstanceSnapshot resources.
type instanceSnapshotState struct {
	CreatedAt *float64 `pulumi:"createdAt"`
	Instance  *string  `pulumi:"instance"`
	Name      *string  `pulumi:"name"`
	Project   *string  `pulumi:"project"`
	Remote    *string  `pulumi:"remote"`
	Stateful  *bool    `pulumi:"stateful"`
}

type InstanceSnapshotState struct {
	CreatedAt pulumi.Float64PtrInput
	Instance  pulumi.StringPtrInput
	Name      pulumi.StringPtrInput
	Project   pulumi.StringPtrInput
	Remote    pulumi.StringPtrInput
	Stateful  pulumi.BoolPtrInput
}

func (InstanceSnapshotState) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceSnapshotState)(nil)).Elem()
}

type instanceSnapshotArgs struct {
	Instance string  `pulumi:"instance"`
	Name     *string `pulumi:"name"`
	Project  *string `pulumi:"project"`
	Remote   *string `pulumi:"remote"`
	Stateful *bool   `pulumi:"stateful"`
}

// The set of arguments for constructing a InstanceSnapshot resource.
type InstanceSnapshotArgs struct {
	Instance pulumi.StringInput
	Name     pulumi.StringPtrInput
	Project  pulumi.StringPtrInput
	Remote   pulumi.StringPtrInput
	Stateful pulumi.BoolPtrInput
}

func (InstanceSnapshotArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*instanceSnapshotArgs)(nil)).Elem()
}

type InstanceSnapshotInput interface {
	pulumi.Input

	ToInstanceSnapshotOutput() InstanceSnapshotOutput
	ToInstanceSnapshotOutputWithContext(ctx context.Context) InstanceSnapshotOutput
}

func (*InstanceSnapshot) ElementType() reflect.Type {
	return reflect.TypeOf((**InstanceSnapshot)(nil)).Elem()
}

func (i *InstanceSnapshot) ToInstanceSnapshotOutput() InstanceSnapshotOutput {
	return i.ToInstanceSnapshotOutputWithContext(context.Background())
}

func (i *InstanceSnapshot) ToInstanceSnapshotOutputWithContext(ctx context.Context) InstanceSnapshotOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InstanceSnapshotOutput)
}

type InstanceSnapshotOutput struct{ *pulumi.OutputState }

func (InstanceSnapshotOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InstanceSnapshot)(nil)).Elem()
}

func (o InstanceSnapshotOutput) ToInstanceSnapshotOutput() InstanceSnapshotOutput {
	return o
}

func (o InstanceSnapshotOutput) ToInstanceSnapshotOutputWithContext(ctx context.Context) InstanceSnapshotOutput {
	return o
}

func (o InstanceSnapshotOutput) CreatedAt() pulumi.Float64Output {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.Float64Output { return v.CreatedAt }).(pulumi.Float64Output)
}

func (o InstanceSnapshotOutput) Instance() pulumi.StringOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.StringOutput { return v.Instance }).(pulumi.StringOutput)
}

func (o InstanceSnapshotOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o InstanceSnapshotOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o InstanceSnapshotOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o InstanceSnapshotOutput) Stateful() pulumi.BoolOutput {
	return o.ApplyT(func(v *InstanceSnapshot) pulumi.BoolOutput { return v.Stateful }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InstanceSnapshotInput)(nil)).Elem(), &InstanceSnapshot{})
	pulumi.RegisterOutputType(InstanceSnapshotOutput{})
}
