// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetworkForward struct {
	pulumi.CustomResourceState

	Config        pulumi.StringMapOutput        `pulumi:"config"`
	Description   pulumi.StringOutput           `pulumi:"description"`
	ListenAddress pulumi.StringOutput           `pulumi:"listenAddress"`
	Network       pulumi.StringOutput           `pulumi:"network"`
	Ports         NetworkForwardPortArrayOutput `pulumi:"ports"`
	Project       pulumi.StringPtrOutput        `pulumi:"project"`
	Remote        pulumi.StringPtrOutput        `pulumi:"remote"`
}

// NewNetworkForward registers a new resource with the given unique name, arguments, and options.
func NewNetworkForward(ctx *pulumi.Context,
	name string, args *NetworkForwardArgs, opts ...pulumi.ResourceOption) (*NetworkForward, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ListenAddress == nil {
		return nil, errors.New("invalid value for required argument 'ListenAddress'")
	}
	if args.Network == nil {
		return nil, errors.New("invalid value for required argument 'Network'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetworkForward
	err = ctx.RegisterPackageResource("incus:index/networkForward:NetworkForward", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkForward gets an existing NetworkForward resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkForward(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkForwardState, opts ...pulumi.ResourceOption) (*NetworkForward, error) {
	var resource NetworkForward
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/networkForward:NetworkForward", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkForward resources.
type networkForwardState struct {
	Config        map[string]string    `pulumi:"config"`
	Description   *string              `pulumi:"description"`
	ListenAddress *string              `pulumi:"listenAddress"`
	Network       *string              `pulumi:"network"`
	Ports         []NetworkForwardPort `pulumi:"ports"`
	Project       *string              `pulumi:"project"`
	Remote        *string              `pulumi:"remote"`
}

type NetworkForwardState struct {
	Config        pulumi.StringMapInput
	Description   pulumi.StringPtrInput
	ListenAddress pulumi.StringPtrInput
	Network       pulumi.StringPtrInput
	Ports         NetworkForwardPortArrayInput
	Project       pulumi.StringPtrInput
	Remote        pulumi.StringPtrInput
}

func (NetworkForwardState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkForwardState)(nil)).Elem()
}

type networkForwardArgs struct {
	Config        map[string]string    `pulumi:"config"`
	Description   *string              `pulumi:"description"`
	ListenAddress string               `pulumi:"listenAddress"`
	Network       string               `pulumi:"network"`
	Ports         []NetworkForwardPort `pulumi:"ports"`
	Project       *string              `pulumi:"project"`
	Remote        *string              `pulumi:"remote"`
}

// The set of arguments for constructing a NetworkForward resource.
type NetworkForwardArgs struct {
	Config        pulumi.StringMapInput
	Description   pulumi.StringPtrInput
	ListenAddress pulumi.StringInput
	Network       pulumi.StringInput
	Ports         NetworkForwardPortArrayInput
	Project       pulumi.StringPtrInput
	Remote        pulumi.StringPtrInput
}

func (NetworkForwardArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkForwardArgs)(nil)).Elem()
}

type NetworkForwardInput interface {
	pulumi.Input

	ToNetworkForwardOutput() NetworkForwardOutput
	ToNetworkForwardOutputWithContext(ctx context.Context) NetworkForwardOutput
}

func (*NetworkForward) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkForward)(nil)).Elem()
}

func (i *NetworkForward) ToNetworkForwardOutput() NetworkForwardOutput {
	return i.ToNetworkForwardOutputWithContext(context.Background())
}

func (i *NetworkForward) ToNetworkForwardOutputWithContext(ctx context.Context) NetworkForwardOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkForwardOutput)
}

type NetworkForwardOutput struct{ *pulumi.OutputState }

func (NetworkForwardOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkForward)(nil)).Elem()
}

func (o NetworkForwardOutput) ToNetworkForwardOutput() NetworkForwardOutput {
	return o
}

func (o NetworkForwardOutput) ToNetworkForwardOutputWithContext(ctx context.Context) NetworkForwardOutput {
	return o
}

func (o NetworkForwardOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NetworkForward) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o NetworkForwardOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkForward) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o NetworkForwardOutput) ListenAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkForward) pulumi.StringOutput { return v.ListenAddress }).(pulumi.StringOutput)
}

func (o NetworkForwardOutput) Network() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkForward) pulumi.StringOutput { return v.Network }).(pulumi.StringOutput)
}

func (o NetworkForwardOutput) Ports() NetworkForwardPortArrayOutput {
	return o.ApplyT(func(v *NetworkForward) NetworkForwardPortArrayOutput { return v.Ports }).(NetworkForwardPortArrayOutput)
}

func (o NetworkForwardOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkForward) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o NetworkForwardOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkForward) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkForwardInput)(nil)).Elem(), &NetworkForward{})
	pulumi.RegisterOutputType(NetworkForwardOutput{})
}
