// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetworkLb struct {
	pulumi.CustomResourceState

	// Network load balancer backend
	Backends      NetworkLbBackendArrayOutput `pulumi:"backends"`
	Config        pulumi.StringMapOutput      `pulumi:"config"`
	Description   pulumi.StringOutput         `pulumi:"description"`
	ListenAddress pulumi.StringOutput         `pulumi:"listenAddress"`
	Network       pulumi.StringOutput         `pulumi:"network"`
	// Network load balancer port
	Ports   NetworkLbPortArrayOutput `pulumi:"ports"`
	Project pulumi.StringPtrOutput   `pulumi:"project"`
	Remote  pulumi.StringPtrOutput   `pulumi:"remote"`
}

// NewNetworkLb registers a new resource with the given unique name, arguments, and options.
func NewNetworkLb(ctx *pulumi.Context,
	name string, args *NetworkLbArgs, opts ...pulumi.ResourceOption) (*NetworkLb, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ListenAddress == nil {
		return nil, errors.New("invalid value for required argument 'ListenAddress'")
	}
	if args.Network == nil {
		return nil, errors.New("invalid value for required argument 'Network'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetworkLb
	err = ctx.RegisterPackageResource("incus:index/networkLb:NetworkLb", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkLb gets an existing NetworkLb resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkLb(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkLbState, opts ...pulumi.ResourceOption) (*NetworkLb, error) {
	var resource NetworkLb
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/networkLb:NetworkLb", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkLb resources.
type networkLbState struct {
	// Network load balancer backend
	Backends      []NetworkLbBackend `pulumi:"backends"`
	Config        map[string]string  `pulumi:"config"`
	Description   *string            `pulumi:"description"`
	ListenAddress *string            `pulumi:"listenAddress"`
	Network       *string            `pulumi:"network"`
	// Network load balancer port
	Ports   []NetworkLbPort `pulumi:"ports"`
	Project *string         `pulumi:"project"`
	Remote  *string         `pulumi:"remote"`
}

type NetworkLbState struct {
	// Network load balancer backend
	Backends      NetworkLbBackendArrayInput
	Config        pulumi.StringMapInput
	Description   pulumi.StringPtrInput
	ListenAddress pulumi.StringPtrInput
	Network       pulumi.StringPtrInput
	// Network load balancer port
	Ports   NetworkLbPortArrayInput
	Project pulumi.StringPtrInput
	Remote  pulumi.StringPtrInput
}

func (NetworkLbState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkLbState)(nil)).Elem()
}

type networkLbArgs struct {
	// Network load balancer backend
	Backends      []NetworkLbBackend `pulumi:"backends"`
	Config        map[string]string  `pulumi:"config"`
	Description   *string            `pulumi:"description"`
	ListenAddress string             `pulumi:"listenAddress"`
	Network       string             `pulumi:"network"`
	// Network load balancer port
	Ports   []NetworkLbPort `pulumi:"ports"`
	Project *string         `pulumi:"project"`
	Remote  *string         `pulumi:"remote"`
}

// The set of arguments for constructing a NetworkLb resource.
type NetworkLbArgs struct {
	// Network load balancer backend
	Backends      NetworkLbBackendArrayInput
	Config        pulumi.StringMapInput
	Description   pulumi.StringPtrInput
	ListenAddress pulumi.StringInput
	Network       pulumi.StringInput
	// Network load balancer port
	Ports   NetworkLbPortArrayInput
	Project pulumi.StringPtrInput
	Remote  pulumi.StringPtrInput
}

func (NetworkLbArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkLbArgs)(nil)).Elem()
}

type NetworkLbInput interface {
	pulumi.Input

	ToNetworkLbOutput() NetworkLbOutput
	ToNetworkLbOutputWithContext(ctx context.Context) NetworkLbOutput
}

func (*NetworkLb) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkLb)(nil)).Elem()
}

func (i *NetworkLb) ToNetworkLbOutput() NetworkLbOutput {
	return i.ToNetworkLbOutputWithContext(context.Background())
}

func (i *NetworkLb) ToNetworkLbOutputWithContext(ctx context.Context) NetworkLbOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkLbOutput)
}

type NetworkLbOutput struct{ *pulumi.OutputState }

func (NetworkLbOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkLb)(nil)).Elem()
}

func (o NetworkLbOutput) ToNetworkLbOutput() NetworkLbOutput {
	return o
}

func (o NetworkLbOutput) ToNetworkLbOutputWithContext(ctx context.Context) NetworkLbOutput {
	return o
}

// Network load balancer backend
func (o NetworkLbOutput) Backends() NetworkLbBackendArrayOutput {
	return o.ApplyT(func(v *NetworkLb) NetworkLbBackendArrayOutput { return v.Backends }).(NetworkLbBackendArrayOutput)
}

func (o NetworkLbOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NetworkLb) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o NetworkLbOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkLb) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o NetworkLbOutput) ListenAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkLb) pulumi.StringOutput { return v.ListenAddress }).(pulumi.StringOutput)
}

func (o NetworkLbOutput) Network() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkLb) pulumi.StringOutput { return v.Network }).(pulumi.StringOutput)
}

// Network load balancer port
func (o NetworkLbOutput) Ports() NetworkLbPortArrayOutput {
	return o.ApplyT(func(v *NetworkLb) NetworkLbPortArrayOutput { return v.Ports }).(NetworkLbPortArrayOutput)
}

func (o NetworkLbOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkLb) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o NetworkLbOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkLb) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkLbInput)(nil)).Elem(), &NetworkLb{})
	pulumi.RegisterOutputType(NetworkLbOutput{})
}
