// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetworkAcl struct {
	pulumi.CustomResourceState

	Config      pulumi.StringMapOutput       `pulumi:"config"`
	Description pulumi.StringOutput          `pulumi:"description"`
	Egresses    NetworkAclEgressArrayOutput  `pulumi:"egresses"`
	Ingresses   NetworkAclIngressArrayOutput `pulumi:"ingresses"`
	Name        pulumi.StringOutput          `pulumi:"name"`
	Project     pulumi.StringPtrOutput       `pulumi:"project"`
	Remote      pulumi.StringPtrOutput       `pulumi:"remote"`
}

// NewNetworkAcl registers a new resource with the given unique name, arguments, and options.
func NewNetworkAcl(ctx *pulumi.Context,
	name string, args *NetworkAclArgs, opts ...pulumi.ResourceOption) (*NetworkAcl, error) {
	if args == nil {
		args = &NetworkAclArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetworkAcl
	err = ctx.RegisterPackageResource("incus:index/networkAcl:NetworkAcl", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkAcl gets an existing NetworkAcl resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkAcl(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkAclState, opts ...pulumi.ResourceOption) (*NetworkAcl, error) {
	var resource NetworkAcl
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/networkAcl:NetworkAcl", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkAcl resources.
type networkAclState struct {
	Config      map[string]string   `pulumi:"config"`
	Description *string             `pulumi:"description"`
	Egresses    []NetworkAclEgress  `pulumi:"egresses"`
	Ingresses   []NetworkAclIngress `pulumi:"ingresses"`
	Name        *string             `pulumi:"name"`
	Project     *string             `pulumi:"project"`
	Remote      *string             `pulumi:"remote"`
}

type NetworkAclState struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Egresses    NetworkAclEgressArrayInput
	Ingresses   NetworkAclIngressArrayInput
	Name        pulumi.StringPtrInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
}

func (NetworkAclState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkAclState)(nil)).Elem()
}

type networkAclArgs struct {
	Config      map[string]string   `pulumi:"config"`
	Description *string             `pulumi:"description"`
	Egresses    []NetworkAclEgress  `pulumi:"egresses"`
	Ingresses   []NetworkAclIngress `pulumi:"ingresses"`
	Name        *string             `pulumi:"name"`
	Project     *string             `pulumi:"project"`
	Remote      *string             `pulumi:"remote"`
}

// The set of arguments for constructing a NetworkAcl resource.
type NetworkAclArgs struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Egresses    NetworkAclEgressArrayInput
	Ingresses   NetworkAclIngressArrayInput
	Name        pulumi.StringPtrInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
}

func (NetworkAclArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkAclArgs)(nil)).Elem()
}

type NetworkAclInput interface {
	pulumi.Input

	ToNetworkAclOutput() NetworkAclOutput
	ToNetworkAclOutputWithContext(ctx context.Context) NetworkAclOutput
}

func (*NetworkAcl) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkAcl)(nil)).Elem()
}

func (i *NetworkAcl) ToNetworkAclOutput() NetworkAclOutput {
	return i.ToNetworkAclOutputWithContext(context.Background())
}

func (i *NetworkAcl) ToNetworkAclOutputWithContext(ctx context.Context) NetworkAclOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkAclOutput)
}

type NetworkAclOutput struct{ *pulumi.OutputState }

func (NetworkAclOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkAcl)(nil)).Elem()
}

func (o NetworkAclOutput) ToNetworkAclOutput() NetworkAclOutput {
	return o
}

func (o NetworkAclOutput) ToNetworkAclOutputWithContext(ctx context.Context) NetworkAclOutput {
	return o
}

func (o NetworkAclOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NetworkAcl) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o NetworkAclOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkAcl) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o NetworkAclOutput) Egresses() NetworkAclEgressArrayOutput {
	return o.ApplyT(func(v *NetworkAcl) NetworkAclEgressArrayOutput { return v.Egresses }).(NetworkAclEgressArrayOutput)
}

func (o NetworkAclOutput) Ingresses() NetworkAclIngressArrayOutput {
	return o.ApplyT(func(v *NetworkAcl) NetworkAclIngressArrayOutput { return v.Ingresses }).(NetworkAclIngressArrayOutput)
}

func (o NetworkAclOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkAcl) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o NetworkAclOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkAcl) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o NetworkAclOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkAcl) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkAclInput)(nil)).Elem(), &NetworkAcl{})
	pulumi.RegisterOutputType(NetworkAclOutput{})
}
