// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetworkZone struct {
	pulumi.CustomResourceState

	Config      pulumi.StringMapOutput `pulumi:"config"`
	Description pulumi.StringOutput    `pulumi:"description"`
	Name        pulumi.StringOutput    `pulumi:"name"`
	Project     pulumi.StringPtrOutput `pulumi:"project"`
	Remote      pulumi.StringPtrOutput `pulumi:"remote"`
}

// NewNetworkZone registers a new resource with the given unique name, arguments, and options.
func NewNetworkZone(ctx *pulumi.Context,
	name string, args *NetworkZoneArgs, opts ...pulumi.ResourceOption) (*NetworkZone, error) {
	if args == nil {
		args = &NetworkZoneArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetworkZone
	err = ctx.RegisterPackageResource("incus:index/networkZone:NetworkZone", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkZone gets an existing NetworkZone resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkZone(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkZoneState, opts ...pulumi.ResourceOption) (*NetworkZone, error) {
	var resource NetworkZone
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/networkZone:NetworkZone", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkZone resources.
type networkZoneState struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Name        *string           `pulumi:"name"`
	Project     *string           `pulumi:"project"`
	Remote      *string           `pulumi:"remote"`
}

type NetworkZoneState struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
}

func (NetworkZoneState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkZoneState)(nil)).Elem()
}

type networkZoneArgs struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Name        *string           `pulumi:"name"`
	Project     *string           `pulumi:"project"`
	Remote      *string           `pulumi:"remote"`
}

// The set of arguments for constructing a NetworkZone resource.
type NetworkZoneArgs struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
}

func (NetworkZoneArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkZoneArgs)(nil)).Elem()
}

type NetworkZoneInput interface {
	pulumi.Input

	ToNetworkZoneOutput() NetworkZoneOutput
	ToNetworkZoneOutputWithContext(ctx context.Context) NetworkZoneOutput
}

func (*NetworkZone) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkZone)(nil)).Elem()
}

func (i *NetworkZone) ToNetworkZoneOutput() NetworkZoneOutput {
	return i.ToNetworkZoneOutputWithContext(context.Background())
}

func (i *NetworkZone) ToNetworkZoneOutputWithContext(ctx context.Context) NetworkZoneOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkZoneOutput)
}

type NetworkZoneOutput struct{ *pulumi.OutputState }

func (NetworkZoneOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkZone)(nil)).Elem()
}

func (o NetworkZoneOutput) ToNetworkZoneOutput() NetworkZoneOutput {
	return o
}

func (o NetworkZoneOutput) ToNetworkZoneOutputWithContext(ctx context.Context) NetworkZoneOutput {
	return o
}

func (o NetworkZoneOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NetworkZone) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o NetworkZoneOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkZone) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o NetworkZoneOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkZone) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o NetworkZoneOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkZone) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o NetworkZoneOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkZone) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkZoneInput)(nil)).Elem(), &NetworkZone{})
	pulumi.RegisterOutputType(NetworkZoneOutput{})
}
