// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetworkPeer struct {
	pulumi.CustomResourceState

	Config            pulumi.StringMapOutput `pulumi:"config"`
	Description       pulumi.StringOutput    `pulumi:"description"`
	Name              pulumi.StringOutput    `pulumi:"name"`
	Network           pulumi.StringPtrOutput `pulumi:"network"`
	Project           pulumi.StringPtrOutput `pulumi:"project"`
	Remote            pulumi.StringPtrOutput `pulumi:"remote"`
	Status            pulumi.StringOutput    `pulumi:"status"`
	TargetIntegration pulumi.StringOutput    `pulumi:"targetIntegration"`
	TargetNetwork     pulumi.StringOutput    `pulumi:"targetNetwork"`
	TargetProject     pulumi.StringOutput    `pulumi:"targetProject"`
	Type              pulumi.StringOutput    `pulumi:"type"`
}

// NewNetworkPeer registers a new resource with the given unique name, arguments, and options.
func NewNetworkPeer(ctx *pulumi.Context,
	name string, args *NetworkPeerArgs, opts ...pulumi.ResourceOption) (*NetworkPeer, error) {
	if args == nil {
		args = &NetworkPeerArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetworkPeer
	err = ctx.RegisterPackageResource("incus:index/networkPeer:NetworkPeer", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkPeer gets an existing NetworkPeer resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkPeer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkPeerState, opts ...pulumi.ResourceOption) (*NetworkPeer, error) {
	var resource NetworkPeer
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/networkPeer:NetworkPeer", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkPeer resources.
type networkPeerState struct {
	Config            map[string]string `pulumi:"config"`
	Description       *string           `pulumi:"description"`
	Name              *string           `pulumi:"name"`
	Network           *string           `pulumi:"network"`
	Project           *string           `pulumi:"project"`
	Remote            *string           `pulumi:"remote"`
	Status            *string           `pulumi:"status"`
	TargetIntegration *string           `pulumi:"targetIntegration"`
	TargetNetwork     *string           `pulumi:"targetNetwork"`
	TargetProject     *string           `pulumi:"targetProject"`
	Type              *string           `pulumi:"type"`
}

type NetworkPeerState struct {
	Config            pulumi.StringMapInput
	Description       pulumi.StringPtrInput
	Name              pulumi.StringPtrInput
	Network           pulumi.StringPtrInput
	Project           pulumi.StringPtrInput
	Remote            pulumi.StringPtrInput
	Status            pulumi.StringPtrInput
	TargetIntegration pulumi.StringPtrInput
	TargetNetwork     pulumi.StringPtrInput
	TargetProject     pulumi.StringPtrInput
	Type              pulumi.StringPtrInput
}

func (NetworkPeerState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkPeerState)(nil)).Elem()
}

type networkPeerArgs struct {
	Config            map[string]string `pulumi:"config"`
	Description       *string           `pulumi:"description"`
	Name              *string           `pulumi:"name"`
	Network           *string           `pulumi:"network"`
	Project           *string           `pulumi:"project"`
	Remote            *string           `pulumi:"remote"`
	TargetIntegration *string           `pulumi:"targetIntegration"`
	TargetNetwork     *string           `pulumi:"targetNetwork"`
	TargetProject     *string           `pulumi:"targetProject"`
	Type              *string           `pulumi:"type"`
}

// The set of arguments for constructing a NetworkPeer resource.
type NetworkPeerArgs struct {
	Config            pulumi.StringMapInput
	Description       pulumi.StringPtrInput
	Name              pulumi.StringPtrInput
	Network           pulumi.StringPtrInput
	Project           pulumi.StringPtrInput
	Remote            pulumi.StringPtrInput
	TargetIntegration pulumi.StringPtrInput
	TargetNetwork     pulumi.StringPtrInput
	TargetProject     pulumi.StringPtrInput
	Type              pulumi.StringPtrInput
}

func (NetworkPeerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkPeerArgs)(nil)).Elem()
}

type NetworkPeerInput interface {
	pulumi.Input

	ToNetworkPeerOutput() NetworkPeerOutput
	ToNetworkPeerOutputWithContext(ctx context.Context) NetworkPeerOutput
}

func (*NetworkPeer) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkPeer)(nil)).Elem()
}

func (i *NetworkPeer) ToNetworkPeerOutput() NetworkPeerOutput {
	return i.ToNetworkPeerOutputWithContext(context.Background())
}

func (i *NetworkPeer) ToNetworkPeerOutputWithContext(ctx context.Context) NetworkPeerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkPeerOutput)
}

type NetworkPeerOutput struct{ *pulumi.OutputState }

func (NetworkPeerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkPeer)(nil)).Elem()
}

func (o NetworkPeerOutput) ToNetworkPeerOutput() NetworkPeerOutput {
	return o
}

func (o NetworkPeerOutput) ToNetworkPeerOutputWithContext(ctx context.Context) NetworkPeerOutput {
	return o
}

func (o NetworkPeerOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NetworkPeer) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o NetworkPeerOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkPeer) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o NetworkPeerOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkPeer) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o NetworkPeerOutput) Network() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkPeer) pulumi.StringPtrOutput { return v.Network }).(pulumi.StringPtrOutput)
}

func (o NetworkPeerOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkPeer) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o NetworkPeerOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkPeer) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o NetworkPeerOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkPeer) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o NetworkPeerOutput) TargetIntegration() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkPeer) pulumi.StringOutput { return v.TargetIntegration }).(pulumi.StringOutput)
}

func (o NetworkPeerOutput) TargetNetwork() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkPeer) pulumi.StringOutput { return v.TargetNetwork }).(pulumi.StringOutput)
}

func (o NetworkPeerOutput) TargetProject() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkPeer) pulumi.StringOutput { return v.TargetProject }).(pulumi.StringOutput)
}

func (o NetworkPeerOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkPeer) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkPeerInput)(nil)).Elem(), &NetworkPeer{})
	pulumi.RegisterOutputType(NetworkPeerOutput{})
}
