// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetworkZoneRecord struct {
	pulumi.CustomResourceState

	Config      pulumi.StringMapOutput `pulumi:"config"`
	Description pulumi.StringOutput    `pulumi:"description"`
	// Network zone record entry
	Entries NetworkZoneRecordEntryArrayOutput `pulumi:"entries"`
	Name    pulumi.StringOutput               `pulumi:"name"`
	Project pulumi.StringPtrOutput            `pulumi:"project"`
	Remote  pulumi.StringPtrOutput            `pulumi:"remote"`
	Zone    pulumi.StringOutput               `pulumi:"zone"`
}

// NewNetworkZoneRecord registers a new resource with the given unique name, arguments, and options.
func NewNetworkZoneRecord(ctx *pulumi.Context,
	name string, args *NetworkZoneRecordArgs, opts ...pulumi.ResourceOption) (*NetworkZoneRecord, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Zone == nil {
		return nil, errors.New("invalid value for required argument 'Zone'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetworkZoneRecord
	err = ctx.RegisterPackageResource("incus:index/networkZoneRecord:NetworkZoneRecord", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkZoneRecord gets an existing NetworkZoneRecord resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkZoneRecord(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkZoneRecordState, opts ...pulumi.ResourceOption) (*NetworkZoneRecord, error) {
	var resource NetworkZoneRecord
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/networkZoneRecord:NetworkZoneRecord", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkZoneRecord resources.
type networkZoneRecordState struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	// Network zone record entry
	Entries []NetworkZoneRecordEntry `pulumi:"entries"`
	Name    *string                  `pulumi:"name"`
	Project *string                  `pulumi:"project"`
	Remote  *string                  `pulumi:"remote"`
	Zone    *string                  `pulumi:"zone"`
}

type NetworkZoneRecordState struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	// Network zone record entry
	Entries NetworkZoneRecordEntryArrayInput
	Name    pulumi.StringPtrInput
	Project pulumi.StringPtrInput
	Remote  pulumi.StringPtrInput
	Zone    pulumi.StringPtrInput
}

func (NetworkZoneRecordState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkZoneRecordState)(nil)).Elem()
}

type networkZoneRecordArgs struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	// Network zone record entry
	Entries []NetworkZoneRecordEntry `pulumi:"entries"`
	Name    *string                  `pulumi:"name"`
	Project *string                  `pulumi:"project"`
	Remote  *string                  `pulumi:"remote"`
	Zone    string                   `pulumi:"zone"`
}

// The set of arguments for constructing a NetworkZoneRecord resource.
type NetworkZoneRecordArgs struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	// Network zone record entry
	Entries NetworkZoneRecordEntryArrayInput
	Name    pulumi.StringPtrInput
	Project pulumi.StringPtrInput
	Remote  pulumi.StringPtrInput
	Zone    pulumi.StringInput
}

func (NetworkZoneRecordArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkZoneRecordArgs)(nil)).Elem()
}

type NetworkZoneRecordInput interface {
	pulumi.Input

	ToNetworkZoneRecordOutput() NetworkZoneRecordOutput
	ToNetworkZoneRecordOutputWithContext(ctx context.Context) NetworkZoneRecordOutput
}

func (*NetworkZoneRecord) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkZoneRecord)(nil)).Elem()
}

func (i *NetworkZoneRecord) ToNetworkZoneRecordOutput() NetworkZoneRecordOutput {
	return i.ToNetworkZoneRecordOutputWithContext(context.Background())
}

func (i *NetworkZoneRecord) ToNetworkZoneRecordOutputWithContext(ctx context.Context) NetworkZoneRecordOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkZoneRecordOutput)
}

type NetworkZoneRecordOutput struct{ *pulumi.OutputState }

func (NetworkZoneRecordOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkZoneRecord)(nil)).Elem()
}

func (o NetworkZoneRecordOutput) ToNetworkZoneRecordOutput() NetworkZoneRecordOutput {
	return o
}

func (o NetworkZoneRecordOutput) ToNetworkZoneRecordOutputWithContext(ctx context.Context) NetworkZoneRecordOutput {
	return o
}

func (o NetworkZoneRecordOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NetworkZoneRecord) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o NetworkZoneRecordOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkZoneRecord) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Network zone record entry
func (o NetworkZoneRecordOutput) Entries() NetworkZoneRecordEntryArrayOutput {
	return o.ApplyT(func(v *NetworkZoneRecord) NetworkZoneRecordEntryArrayOutput { return v.Entries }).(NetworkZoneRecordEntryArrayOutput)
}

func (o NetworkZoneRecordOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkZoneRecord) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o NetworkZoneRecordOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkZoneRecord) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o NetworkZoneRecordOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkZoneRecord) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o NetworkZoneRecordOutput) Zone() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkZoneRecord) pulumi.StringOutput { return v.Zone }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkZoneRecordInput)(nil)).Elem(), &NetworkZoneRecord{})
	pulumi.RegisterOutputType(NetworkZoneRecordOutput{})
}
