// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetworkIntegration struct {
	pulumi.CustomResourceState

	Config      pulumi.StringMapOutput `pulumi:"config"`
	Description pulumi.StringOutput    `pulumi:"description"`
	Name        pulumi.StringOutput    `pulumi:"name"`
	Project     pulumi.StringPtrOutput `pulumi:"project"`
	Remote      pulumi.StringPtrOutput `pulumi:"remote"`
	Type        pulumi.StringOutput    `pulumi:"type"`
}

// NewNetworkIntegration registers a new resource with the given unique name, arguments, and options.
func NewNetworkIntegration(ctx *pulumi.Context,
	name string, args *NetworkIntegrationArgs, opts ...pulumi.ResourceOption) (*NetworkIntegration, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetworkIntegration
	err = ctx.RegisterPackageResource("incus:index/networkIntegration:NetworkIntegration", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkIntegration gets an existing NetworkIntegration resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkIntegration(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkIntegrationState, opts ...pulumi.ResourceOption) (*NetworkIntegration, error) {
	var resource NetworkIntegration
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/networkIntegration:NetworkIntegration", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkIntegration resources.
type networkIntegrationState struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Name        *string           `pulumi:"name"`
	Project     *string           `pulumi:"project"`
	Remote      *string           `pulumi:"remote"`
	Type        *string           `pulumi:"type"`
}

type NetworkIntegrationState struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
	Type        pulumi.StringPtrInput
}

func (NetworkIntegrationState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkIntegrationState)(nil)).Elem()
}

type networkIntegrationArgs struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Name        *string           `pulumi:"name"`
	Project     *string           `pulumi:"project"`
	Remote      *string           `pulumi:"remote"`
	Type        string            `pulumi:"type"`
}

// The set of arguments for constructing a NetworkIntegration resource.
type NetworkIntegrationArgs struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
	Type        pulumi.StringInput
}

func (NetworkIntegrationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkIntegrationArgs)(nil)).Elem()
}

type NetworkIntegrationInput interface {
	pulumi.Input

	ToNetworkIntegrationOutput() NetworkIntegrationOutput
	ToNetworkIntegrationOutputWithContext(ctx context.Context) NetworkIntegrationOutput
}

func (*NetworkIntegration) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkIntegration)(nil)).Elem()
}

func (i *NetworkIntegration) ToNetworkIntegrationOutput() NetworkIntegrationOutput {
	return i.ToNetworkIntegrationOutputWithContext(context.Background())
}

func (i *NetworkIntegration) ToNetworkIntegrationOutputWithContext(ctx context.Context) NetworkIntegrationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkIntegrationOutput)
}

type NetworkIntegrationOutput struct{ *pulumi.OutputState }

func (NetworkIntegrationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkIntegration)(nil)).Elem()
}

func (o NetworkIntegrationOutput) ToNetworkIntegrationOutput() NetworkIntegrationOutput {
	return o
}

func (o NetworkIntegrationOutput) ToNetworkIntegrationOutputWithContext(ctx context.Context) NetworkIntegrationOutput {
	return o
}

func (o NetworkIntegrationOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NetworkIntegration) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o NetworkIntegrationOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkIntegration) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o NetworkIntegrationOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkIntegration) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o NetworkIntegrationOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkIntegration) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o NetworkIntegrationOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkIntegration) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o NetworkIntegrationOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkIntegration) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkIntegrationInput)(nil)).Elem(), &NetworkIntegration{})
	pulumi.RegisterOutputType(NetworkIntegrationOutput{})
}
