// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type NetworkAddressSet struct {
	pulumi.CustomResourceState

	Addresses   pulumi.StringArrayOutput `pulumi:"addresses"`
	Config      pulumi.StringMapOutput   `pulumi:"config"`
	Description pulumi.StringOutput      `pulumi:"description"`
	Name        pulumi.StringOutput      `pulumi:"name"`
	Project     pulumi.StringPtrOutput   `pulumi:"project"`
	Remote      pulumi.StringPtrOutput   `pulumi:"remote"`
}

// NewNetworkAddressSet registers a new resource with the given unique name, arguments, and options.
func NewNetworkAddressSet(ctx *pulumi.Context,
	name string, args *NetworkAddressSetArgs, opts ...pulumi.ResourceOption) (*NetworkAddressSet, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Addresses == nil {
		return nil, errors.New("invalid value for required argument 'Addresses'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource NetworkAddressSet
	err = ctx.RegisterPackageResource("incus:index/networkAddressSet:NetworkAddressSet", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNetworkAddressSet gets an existing NetworkAddressSet resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNetworkAddressSet(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NetworkAddressSetState, opts ...pulumi.ResourceOption) (*NetworkAddressSet, error) {
	var resource NetworkAddressSet
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/networkAddressSet:NetworkAddressSet", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NetworkAddressSet resources.
type networkAddressSetState struct {
	Addresses   []string          `pulumi:"addresses"`
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Name        *string           `pulumi:"name"`
	Project     *string           `pulumi:"project"`
	Remote      *string           `pulumi:"remote"`
}

type NetworkAddressSetState struct {
	Addresses   pulumi.StringArrayInput
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
}

func (NetworkAddressSetState) ElementType() reflect.Type {
	return reflect.TypeOf((*networkAddressSetState)(nil)).Elem()
}

type networkAddressSetArgs struct {
	Addresses   []string          `pulumi:"addresses"`
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Name        *string           `pulumi:"name"`
	Project     *string           `pulumi:"project"`
	Remote      *string           `pulumi:"remote"`
}

// The set of arguments for constructing a NetworkAddressSet resource.
type NetworkAddressSetArgs struct {
	Addresses   pulumi.StringArrayInput
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
}

func (NetworkAddressSetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*networkAddressSetArgs)(nil)).Elem()
}

type NetworkAddressSetInput interface {
	pulumi.Input

	ToNetworkAddressSetOutput() NetworkAddressSetOutput
	ToNetworkAddressSetOutputWithContext(ctx context.Context) NetworkAddressSetOutput
}

func (*NetworkAddressSet) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkAddressSet)(nil)).Elem()
}

func (i *NetworkAddressSet) ToNetworkAddressSetOutput() NetworkAddressSetOutput {
	return i.ToNetworkAddressSetOutputWithContext(context.Background())
}

func (i *NetworkAddressSet) ToNetworkAddressSetOutputWithContext(ctx context.Context) NetworkAddressSetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkAddressSetOutput)
}

type NetworkAddressSetOutput struct{ *pulumi.OutputState }

func (NetworkAddressSetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NetworkAddressSet)(nil)).Elem()
}

func (o NetworkAddressSetOutput) ToNetworkAddressSetOutput() NetworkAddressSetOutput {
	return o
}

func (o NetworkAddressSetOutput) ToNetworkAddressSetOutputWithContext(ctx context.Context) NetworkAddressSetOutput {
	return o
}

func (o NetworkAddressSetOutput) Addresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *NetworkAddressSet) pulumi.StringArrayOutput { return v.Addresses }).(pulumi.StringArrayOutput)
}

func (o NetworkAddressSetOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *NetworkAddressSet) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o NetworkAddressSetOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkAddressSet) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o NetworkAddressSetOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NetworkAddressSet) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o NetworkAddressSetOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkAddressSet) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o NetworkAddressSetOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *NetworkAddressSet) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NetworkAddressSetInput)(nil)).Elem(), &NetworkAddressSet{})
	pulumi.RegisterOutputType(NetworkAddressSetOutput{})
}
