// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Profile struct {
	pulumi.CustomResourceState

	Config      pulumi.StringMapOutput `pulumi:"config"`
	Description pulumi.StringOutput    `pulumi:"description"`
	// Profile device
	Devices ProfileDeviceArrayOutput `pulumi:"devices"`
	Name    pulumi.StringOutput      `pulumi:"name"`
	Project pulumi.StringOutput      `pulumi:"project"`
	Remote  pulumi.StringPtrOutput   `pulumi:"remote"`
}

// NewProfile registers a new resource with the given unique name, arguments, and options.
func NewProfile(ctx *pulumi.Context,
	name string, args *ProfileArgs, opts ...pulumi.ResourceOption) (*Profile, error) {
	if args == nil {
		args = &ProfileArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource Profile
	err = ctx.RegisterPackageResource("incus:index/profile:Profile", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProfile gets an existing Profile resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProfile(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProfileState, opts ...pulumi.ResourceOption) (*Profile, error) {
	var resource Profile
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/profile:Profile", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Profile resources.
type profileState struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	// Profile device
	Devices []ProfileDevice `pulumi:"devices"`
	Name    *string         `pulumi:"name"`
	Project *string         `pulumi:"project"`
	Remote  *string         `pulumi:"remote"`
}

type ProfileState struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	// Profile device
	Devices ProfileDeviceArrayInput
	Name    pulumi.StringPtrInput
	Project pulumi.StringPtrInput
	Remote  pulumi.StringPtrInput
}

func (ProfileState) ElementType() reflect.Type {
	return reflect.TypeOf((*profileState)(nil)).Elem()
}

type profileArgs struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	// Profile device
	Devices []ProfileDevice `pulumi:"devices"`
	Name    *string         `pulumi:"name"`
	Project *string         `pulumi:"project"`
	Remote  *string         `pulumi:"remote"`
}

// The set of arguments for constructing a Profile resource.
type ProfileArgs struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	// Profile device
	Devices ProfileDeviceArrayInput
	Name    pulumi.StringPtrInput
	Project pulumi.StringPtrInput
	Remote  pulumi.StringPtrInput
}

func (ProfileArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*profileArgs)(nil)).Elem()
}

type ProfileInput interface {
	pulumi.Input

	ToProfileOutput() ProfileOutput
	ToProfileOutputWithContext(ctx context.Context) ProfileOutput
}

func (*Profile) ElementType() reflect.Type {
	return reflect.TypeOf((**Profile)(nil)).Elem()
}

func (i *Profile) ToProfileOutput() ProfileOutput {
	return i.ToProfileOutputWithContext(context.Background())
}

func (i *Profile) ToProfileOutputWithContext(ctx context.Context) ProfileOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProfileOutput)
}

type ProfileOutput struct{ *pulumi.OutputState }

func (ProfileOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Profile)(nil)).Elem()
}

func (o ProfileOutput) ToProfileOutput() ProfileOutput {
	return o
}

func (o ProfileOutput) ToProfileOutputWithContext(ctx context.Context) ProfileOutput {
	return o
}

func (o ProfileOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *Profile) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o ProfileOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Profile) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Profile device
func (o ProfileOutput) Devices() ProfileDeviceArrayOutput {
	return o.ApplyT(func(v *Profile) ProfileDeviceArrayOutput { return v.Devices }).(ProfileDeviceArrayOutput)
}

func (o ProfileOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Profile) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o ProfileOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *Profile) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

func (o ProfileOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Profile) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProfileInput)(nil)).Elem(), &Profile{})
	pulumi.RegisterOutputType(ProfileOutput{})
}
