// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type StorageBucketKey struct {
	pulumi.CustomResourceState

	AccessKey     pulumi.StringOutput    `pulumi:"accessKey"`
	Description   pulumi.StringOutput    `pulumi:"description"`
	Name          pulumi.StringOutput    `pulumi:"name"`
	Pool          pulumi.StringOutput    `pulumi:"pool"`
	Project       pulumi.StringPtrOutput `pulumi:"project"`
	Remote        pulumi.StringPtrOutput `pulumi:"remote"`
	Role          pulumi.StringOutput    `pulumi:"role"`
	SecretKey     pulumi.StringOutput    `pulumi:"secretKey"`
	StorageBucket pulumi.StringOutput    `pulumi:"storageBucket"`
}

// NewStorageBucketKey registers a new resource with the given unique name, arguments, and options.
func NewStorageBucketKey(ctx *pulumi.Context,
	name string, args *StorageBucketKeyArgs, opts ...pulumi.ResourceOption) (*StorageBucketKey, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Pool == nil {
		return nil, errors.New("invalid value for required argument 'Pool'")
	}
	if args.StorageBucket == nil {
		return nil, errors.New("invalid value for required argument 'StorageBucket'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"accessKey",
		"secretKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource StorageBucketKey
	err = ctx.RegisterPackageResource("incus:index/storageBucketKey:StorageBucketKey", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetStorageBucketKey gets an existing StorageBucketKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetStorageBucketKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *StorageBucketKeyState, opts ...pulumi.ResourceOption) (*StorageBucketKey, error) {
	var resource StorageBucketKey
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/storageBucketKey:StorageBucketKey", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering StorageBucketKey resources.
type storageBucketKeyState struct {
	AccessKey     *string `pulumi:"accessKey"`
	Description   *string `pulumi:"description"`
	Name          *string `pulumi:"name"`
	Pool          *string `pulumi:"pool"`
	Project       *string `pulumi:"project"`
	Remote        *string `pulumi:"remote"`
	Role          *string `pulumi:"role"`
	SecretKey     *string `pulumi:"secretKey"`
	StorageBucket *string `pulumi:"storageBucket"`
}

type StorageBucketKeyState struct {
	AccessKey     pulumi.StringPtrInput
	Description   pulumi.StringPtrInput
	Name          pulumi.StringPtrInput
	Pool          pulumi.StringPtrInput
	Project       pulumi.StringPtrInput
	Remote        pulumi.StringPtrInput
	Role          pulumi.StringPtrInput
	SecretKey     pulumi.StringPtrInput
	StorageBucket pulumi.StringPtrInput
}

func (StorageBucketKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*storageBucketKeyState)(nil)).Elem()
}

type storageBucketKeyArgs struct {
	Description   *string `pulumi:"description"`
	Name          *string `pulumi:"name"`
	Pool          string  `pulumi:"pool"`
	Project       *string `pulumi:"project"`
	Remote        *string `pulumi:"remote"`
	Role          *string `pulumi:"role"`
	StorageBucket string  `pulumi:"storageBucket"`
}

// The set of arguments for constructing a StorageBucketKey resource.
type StorageBucketKeyArgs struct {
	Description   pulumi.StringPtrInput
	Name          pulumi.StringPtrInput
	Pool          pulumi.StringInput
	Project       pulumi.StringPtrInput
	Remote        pulumi.StringPtrInput
	Role          pulumi.StringPtrInput
	StorageBucket pulumi.StringInput
}

func (StorageBucketKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*storageBucketKeyArgs)(nil)).Elem()
}

type StorageBucketKeyInput interface {
	pulumi.Input

	ToStorageBucketKeyOutput() StorageBucketKeyOutput
	ToStorageBucketKeyOutputWithContext(ctx context.Context) StorageBucketKeyOutput
}

func (*StorageBucketKey) ElementType() reflect.Type {
	return reflect.TypeOf((**StorageBucketKey)(nil)).Elem()
}

func (i *StorageBucketKey) ToStorageBucketKeyOutput() StorageBucketKeyOutput {
	return i.ToStorageBucketKeyOutputWithContext(context.Background())
}

func (i *StorageBucketKey) ToStorageBucketKeyOutputWithContext(ctx context.Context) StorageBucketKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StorageBucketKeyOutput)
}

type StorageBucketKeyOutput struct{ *pulumi.OutputState }

func (StorageBucketKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**StorageBucketKey)(nil)).Elem()
}

func (o StorageBucketKeyOutput) ToStorageBucketKeyOutput() StorageBucketKeyOutput {
	return o
}

func (o StorageBucketKeyOutput) ToStorageBucketKeyOutputWithContext(ctx context.Context) StorageBucketKeyOutput {
	return o
}

func (o StorageBucketKeyOutput) AccessKey() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucketKey) pulumi.StringOutput { return v.AccessKey }).(pulumi.StringOutput)
}

func (o StorageBucketKeyOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucketKey) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o StorageBucketKeyOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucketKey) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o StorageBucketKeyOutput) Pool() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucketKey) pulumi.StringOutput { return v.Pool }).(pulumi.StringOutput)
}

func (o StorageBucketKeyOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StorageBucketKey) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o StorageBucketKeyOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StorageBucketKey) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o StorageBucketKeyOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucketKey) pulumi.StringOutput { return v.Role }).(pulumi.StringOutput)
}

func (o StorageBucketKeyOutput) SecretKey() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucketKey) pulumi.StringOutput { return v.SecretKey }).(pulumi.StringOutput)
}

func (o StorageBucketKeyOutput) StorageBucket() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucketKey) pulumi.StringOutput { return v.StorageBucket }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*StorageBucketKeyInput)(nil)).Elem(), &StorageBucketKey{})
	pulumi.RegisterOutputType(StorageBucketKeyOutput{})
}
