// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type StoragePool struct {
	pulumi.CustomResourceState

	Config      pulumi.StringMapOutput `pulumi:"config"`
	Description pulumi.StringOutput    `pulumi:"description"`
	Driver      pulumi.StringOutput    `pulumi:"driver"`
	Name        pulumi.StringOutput    `pulumi:"name"`
	Project     pulumi.StringPtrOutput `pulumi:"project"`
	Remote      pulumi.StringPtrOutput `pulumi:"remote"`
	Target      pulumi.StringPtrOutput `pulumi:"target"`
}

// NewStoragePool registers a new resource with the given unique name, arguments, and options.
func NewStoragePool(ctx *pulumi.Context,
	name string, args *StoragePoolArgs, opts ...pulumi.ResourceOption) (*StoragePool, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Driver == nil {
		return nil, errors.New("invalid value for required argument 'Driver'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource StoragePool
	err = ctx.RegisterPackageResource("incus:index/storagePool:StoragePool", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetStoragePool gets an existing StoragePool resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetStoragePool(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *StoragePoolState, opts ...pulumi.ResourceOption) (*StoragePool, error) {
	var resource StoragePool
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/storagePool:StoragePool", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering StoragePool resources.
type storagePoolState struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Driver      *string           `pulumi:"driver"`
	Name        *string           `pulumi:"name"`
	Project     *string           `pulumi:"project"`
	Remote      *string           `pulumi:"remote"`
	Target      *string           `pulumi:"target"`
}

type StoragePoolState struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Driver      pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
	Target      pulumi.StringPtrInput
}

func (StoragePoolState) ElementType() reflect.Type {
	return reflect.TypeOf((*storagePoolState)(nil)).Elem()
}

type storagePoolArgs struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Driver      string            `pulumi:"driver"`
	Name        *string           `pulumi:"name"`
	Project     *string           `pulumi:"project"`
	Remote      *string           `pulumi:"remote"`
	Target      *string           `pulumi:"target"`
}

// The set of arguments for constructing a StoragePool resource.
type StoragePoolArgs struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Driver      pulumi.StringInput
	Name        pulumi.StringPtrInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
	Target      pulumi.StringPtrInput
}

func (StoragePoolArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*storagePoolArgs)(nil)).Elem()
}

type StoragePoolInput interface {
	pulumi.Input

	ToStoragePoolOutput() StoragePoolOutput
	ToStoragePoolOutputWithContext(ctx context.Context) StoragePoolOutput
}

func (*StoragePool) ElementType() reflect.Type {
	return reflect.TypeOf((**StoragePool)(nil)).Elem()
}

func (i *StoragePool) ToStoragePoolOutput() StoragePoolOutput {
	return i.ToStoragePoolOutputWithContext(context.Background())
}

func (i *StoragePool) ToStoragePoolOutputWithContext(ctx context.Context) StoragePoolOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StoragePoolOutput)
}

type StoragePoolOutput struct{ *pulumi.OutputState }

func (StoragePoolOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**StoragePool)(nil)).Elem()
}

func (o StoragePoolOutput) ToStoragePoolOutput() StoragePoolOutput {
	return o
}

func (o StoragePoolOutput) ToStoragePoolOutputWithContext(ctx context.Context) StoragePoolOutput {
	return o
}

func (o StoragePoolOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *StoragePool) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o StoragePoolOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *StoragePool) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o StoragePoolOutput) Driver() pulumi.StringOutput {
	return o.ApplyT(func(v *StoragePool) pulumi.StringOutput { return v.Driver }).(pulumi.StringOutput)
}

func (o StoragePoolOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *StoragePool) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o StoragePoolOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StoragePool) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o StoragePoolOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StoragePool) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o StoragePoolOutput) Target() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StoragePool) pulumi.StringPtrOutput { return v.Target }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*StoragePoolInput)(nil)).Elem(), &StoragePool{})
	pulumi.RegisterOutputType(StoragePoolOutput{})
}
