// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type StorageBucket struct {
	pulumi.CustomResourceState

	Config      pulumi.StringMapOutput `pulumi:"config"`
	Description pulumi.StringOutput    `pulumi:"description"`
	Location    pulumi.StringOutput    `pulumi:"location"`
	Name        pulumi.StringOutput    `pulumi:"name"`
	Pool        pulumi.StringOutput    `pulumi:"pool"`
	Project     pulumi.StringPtrOutput `pulumi:"project"`
	Remote      pulumi.StringPtrOutput `pulumi:"remote"`
	SourceFile  pulumi.StringPtrOutput `pulumi:"sourceFile"`
	Target      pulumi.StringOutput    `pulumi:"target"`
}

// NewStorageBucket registers a new resource with the given unique name, arguments, and options.
func NewStorageBucket(ctx *pulumi.Context,
	name string, args *StorageBucketArgs, opts ...pulumi.ResourceOption) (*StorageBucket, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Pool == nil {
		return nil, errors.New("invalid value for required argument 'Pool'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource StorageBucket
	err = ctx.RegisterPackageResource("incus:index/storageBucket:StorageBucket", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetStorageBucket gets an existing StorageBucket resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetStorageBucket(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *StorageBucketState, opts ...pulumi.ResourceOption) (*StorageBucket, error) {
	var resource StorageBucket
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/storageBucket:StorageBucket", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering StorageBucket resources.
type storageBucketState struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Location    *string           `pulumi:"location"`
	Name        *string           `pulumi:"name"`
	Pool        *string           `pulumi:"pool"`
	Project     *string           `pulumi:"project"`
	Remote      *string           `pulumi:"remote"`
	SourceFile  *string           `pulumi:"sourceFile"`
	Target      *string           `pulumi:"target"`
}

type StorageBucketState struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Location    pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Pool        pulumi.StringPtrInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
	SourceFile  pulumi.StringPtrInput
	Target      pulumi.StringPtrInput
}

func (StorageBucketState) ElementType() reflect.Type {
	return reflect.TypeOf((*storageBucketState)(nil)).Elem()
}

type storageBucketArgs struct {
	Config      map[string]string `pulumi:"config"`
	Description *string           `pulumi:"description"`
	Name        *string           `pulumi:"name"`
	Pool        string            `pulumi:"pool"`
	Project     *string           `pulumi:"project"`
	Remote      *string           `pulumi:"remote"`
	SourceFile  *string           `pulumi:"sourceFile"`
	Target      *string           `pulumi:"target"`
}

// The set of arguments for constructing a StorageBucket resource.
type StorageBucketArgs struct {
	Config      pulumi.StringMapInput
	Description pulumi.StringPtrInput
	Name        pulumi.StringPtrInput
	Pool        pulumi.StringInput
	Project     pulumi.StringPtrInput
	Remote      pulumi.StringPtrInput
	SourceFile  pulumi.StringPtrInput
	Target      pulumi.StringPtrInput
}

func (StorageBucketArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*storageBucketArgs)(nil)).Elem()
}

type StorageBucketInput interface {
	pulumi.Input

	ToStorageBucketOutput() StorageBucketOutput
	ToStorageBucketOutputWithContext(ctx context.Context) StorageBucketOutput
}

func (*StorageBucket) ElementType() reflect.Type {
	return reflect.TypeOf((**StorageBucket)(nil)).Elem()
}

func (i *StorageBucket) ToStorageBucketOutput() StorageBucketOutput {
	return i.ToStorageBucketOutputWithContext(context.Background())
}

func (i *StorageBucket) ToStorageBucketOutputWithContext(ctx context.Context) StorageBucketOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StorageBucketOutput)
}

type StorageBucketOutput struct{ *pulumi.OutputState }

func (StorageBucketOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**StorageBucket)(nil)).Elem()
}

func (o StorageBucketOutput) ToStorageBucketOutput() StorageBucketOutput {
	return o
}

func (o StorageBucketOutput) ToStorageBucketOutputWithContext(ctx context.Context) StorageBucketOutput {
	return o
}

func (o StorageBucketOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *StorageBucket) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o StorageBucketOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucket) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o StorageBucketOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucket) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

func (o StorageBucketOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucket) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o StorageBucketOutput) Pool() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucket) pulumi.StringOutput { return v.Pool }).(pulumi.StringOutput)
}

func (o StorageBucketOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StorageBucket) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o StorageBucketOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StorageBucket) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o StorageBucketOutput) SourceFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StorageBucket) pulumi.StringPtrOutput { return v.SourceFile }).(pulumi.StringPtrOutput)
}

func (o StorageBucketOutput) Target() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageBucket) pulumi.StringOutput { return v.Target }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*StorageBucketInput)(nil)).Elem(), &StorageBucket{})
	pulumi.RegisterOutputType(StorageBucketOutput{})
}
