// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package incus

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type StorageVolume struct {
	pulumi.CustomResourceState

	Config       pulumi.StringMapOutput             `pulumi:"config"`
	ContentType  pulumi.StringOutput                `pulumi:"contentType"`
	Description  pulumi.StringOutput                `pulumi:"description"`
	Location     pulumi.StringOutput                `pulumi:"location"`
	Name         pulumi.StringOutput                `pulumi:"name"`
	Pool         pulumi.StringOutput                `pulumi:"pool"`
	Project      pulumi.StringPtrOutput             `pulumi:"project"`
	Remote       pulumi.StringPtrOutput             `pulumi:"remote"`
	SourceFile   pulumi.StringPtrOutput             `pulumi:"sourceFile"`
	SourceVolume StorageVolumeSourceVolumePtrOutput `pulumi:"sourceVolume"`
	Target       pulumi.StringOutput                `pulumi:"target"`
	Type         pulumi.StringOutput                `pulumi:"type"`
}

// NewStorageVolume registers a new resource with the given unique name, arguments, and options.
func NewStorageVolume(ctx *pulumi.Context,
	name string, args *StorageVolumeArgs, opts ...pulumi.ResourceOption) (*StorageVolume, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Pool == nil {
		return nil, errors.New("invalid value for required argument 'Pool'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	var resource StorageVolume
	err = ctx.RegisterPackageResource("incus:index/storageVolume:StorageVolume", name, args, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetStorageVolume gets an existing StorageVolume resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetStorageVolume(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *StorageVolumeState, opts ...pulumi.ResourceOption) (*StorageVolume, error) {
	var resource StorageVolume
	ref, err := internal.PkgGetPackageRef(ctx)
	if err != nil {
		return nil, err
	}
	err = ctx.ReadPackageResource("incus:index/storageVolume:StorageVolume", name, id, state, &resource, ref, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering StorageVolume resources.
type storageVolumeState struct {
	Config       map[string]string          `pulumi:"config"`
	ContentType  *string                    `pulumi:"contentType"`
	Description  *string                    `pulumi:"description"`
	Location     *string                    `pulumi:"location"`
	Name         *string                    `pulumi:"name"`
	Pool         *string                    `pulumi:"pool"`
	Project      *string                    `pulumi:"project"`
	Remote       *string                    `pulumi:"remote"`
	SourceFile   *string                    `pulumi:"sourceFile"`
	SourceVolume *StorageVolumeSourceVolume `pulumi:"sourceVolume"`
	Target       *string                    `pulumi:"target"`
	Type         *string                    `pulumi:"type"`
}

type StorageVolumeState struct {
	Config       pulumi.StringMapInput
	ContentType  pulumi.StringPtrInput
	Description  pulumi.StringPtrInput
	Location     pulumi.StringPtrInput
	Name         pulumi.StringPtrInput
	Pool         pulumi.StringPtrInput
	Project      pulumi.StringPtrInput
	Remote       pulumi.StringPtrInput
	SourceFile   pulumi.StringPtrInput
	SourceVolume StorageVolumeSourceVolumePtrInput
	Target       pulumi.StringPtrInput
	Type         pulumi.StringPtrInput
}

func (StorageVolumeState) ElementType() reflect.Type {
	return reflect.TypeOf((*storageVolumeState)(nil)).Elem()
}

type storageVolumeArgs struct {
	Config       map[string]string          `pulumi:"config"`
	ContentType  *string                    `pulumi:"contentType"`
	Description  *string                    `pulumi:"description"`
	Name         *string                    `pulumi:"name"`
	Pool         string                     `pulumi:"pool"`
	Project      *string                    `pulumi:"project"`
	Remote       *string                    `pulumi:"remote"`
	SourceFile   *string                    `pulumi:"sourceFile"`
	SourceVolume *StorageVolumeSourceVolume `pulumi:"sourceVolume"`
	Target       *string                    `pulumi:"target"`
	Type         *string                    `pulumi:"type"`
}

// The set of arguments for constructing a StorageVolume resource.
type StorageVolumeArgs struct {
	Config       pulumi.StringMapInput
	ContentType  pulumi.StringPtrInput
	Description  pulumi.StringPtrInput
	Name         pulumi.StringPtrInput
	Pool         pulumi.StringInput
	Project      pulumi.StringPtrInput
	Remote       pulumi.StringPtrInput
	SourceFile   pulumi.StringPtrInput
	SourceVolume StorageVolumeSourceVolumePtrInput
	Target       pulumi.StringPtrInput
	Type         pulumi.StringPtrInput
}

func (StorageVolumeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*storageVolumeArgs)(nil)).Elem()
}

type StorageVolumeInput interface {
	pulumi.Input

	ToStorageVolumeOutput() StorageVolumeOutput
	ToStorageVolumeOutputWithContext(ctx context.Context) StorageVolumeOutput
}

func (*StorageVolume) ElementType() reflect.Type {
	return reflect.TypeOf((**StorageVolume)(nil)).Elem()
}

func (i *StorageVolume) ToStorageVolumeOutput() StorageVolumeOutput {
	return i.ToStorageVolumeOutputWithContext(context.Background())
}

func (i *StorageVolume) ToStorageVolumeOutputWithContext(ctx context.Context) StorageVolumeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(StorageVolumeOutput)
}

type StorageVolumeOutput struct{ *pulumi.OutputState }

func (StorageVolumeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**StorageVolume)(nil)).Elem()
}

func (o StorageVolumeOutput) ToStorageVolumeOutput() StorageVolumeOutput {
	return o
}

func (o StorageVolumeOutput) ToStorageVolumeOutputWithContext(ctx context.Context) StorageVolumeOutput {
	return o
}

func (o StorageVolumeOutput) Config() pulumi.StringMapOutput {
	return o.ApplyT(func(v *StorageVolume) pulumi.StringMapOutput { return v.Config }).(pulumi.StringMapOutput)
}

func (o StorageVolumeOutput) ContentType() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageVolume) pulumi.StringOutput { return v.ContentType }).(pulumi.StringOutput)
}

func (o StorageVolumeOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageVolume) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

func (o StorageVolumeOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageVolume) pulumi.StringOutput { return v.Location }).(pulumi.StringOutput)
}

func (o StorageVolumeOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageVolume) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o StorageVolumeOutput) Pool() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageVolume) pulumi.StringOutput { return v.Pool }).(pulumi.StringOutput)
}

func (o StorageVolumeOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StorageVolume) pulumi.StringPtrOutput { return v.Project }).(pulumi.StringPtrOutput)
}

func (o StorageVolumeOutput) Remote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StorageVolume) pulumi.StringPtrOutput { return v.Remote }).(pulumi.StringPtrOutput)
}

func (o StorageVolumeOutput) SourceFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *StorageVolume) pulumi.StringPtrOutput { return v.SourceFile }).(pulumi.StringPtrOutput)
}

func (o StorageVolumeOutput) SourceVolume() StorageVolumeSourceVolumePtrOutput {
	return o.ApplyT(func(v *StorageVolume) StorageVolumeSourceVolumePtrOutput { return v.SourceVolume }).(StorageVolumeSourceVolumePtrOutput)
}

func (o StorageVolumeOutput) Target() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageVolume) pulumi.StringOutput { return v.Target }).(pulumi.StringOutput)
}

func (o StorageVolumeOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *StorageVolume) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*StorageVolumeInput)(nil)).Elem(), &StorageVolume{})
	pulumi.RegisterOutputType(StorageVolumeOutput{})
}
