// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Accept the server certificate.
func GetAcceptRemoteCertificate(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "incus:acceptRemoteCertificate")
}

// The directory to look for existing Incus configuration. (default = $HOME/.config/incus)
func GetConfigDir(ctx *pulumi.Context) string {
	return config.Get(ctx, "incus:configDir")
}

// The default remote to use when no other remote is defined in a resource.
func GetDefaultRemote(ctx *pulumi.Context) string {
	return config.Get(ctx, "incus:defaultRemote")
}

// Automatically generate the Incus client certificates if they don't exist.
func GetGenerateClientCertificates(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "incus:generateClientCertificates")
}

// The project where project-scoped resources will be created. Can be overridden in individual resources. (default = default)
func GetProject(ctx *pulumi.Context) string {
	return config.Get(ctx, "incus:project")
}

// Incus Remote
func GetRemotes(ctx *pulumi.Context) string {
	return config.Get(ctx, "incus:remotes")
}
