// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-terraform-provider/sdks/go/incus/incus/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type Remotes struct {
	// The URL of the Incus host. The default will be the path to the local unix socket, or leaving it as an empty string will use the default socket path.
	Address *string `pulumi:"address"`
	// Server authentication type, tls or oidc. ( Only for the <span pulumi-lang-nodejs="`incus`" pulumi-lang-dotnet="`Incus`" pulumi-lang-go="`incus`" pulumi-lang-python="`incus`" pulumi-lang-yaml="`incus`" pulumi-lang-java="`incus`">`incus`</span> protocol )
	AuthenticationType *string `pulumi:"authenticationType"`
	// Name of the Incus remote.
	Name string `pulumi:"name"`
	// Server protocol ( incus, oci or simplestreams )
	Protocol *string `pulumi:"protocol"`
	// Public image server
	Public *bool `pulumi:"public"`
	// The trust token used for initial authentication with the Incus remote.
	Token *string `pulumi:"token"`
}

// RemotesInput is an input type that accepts RemotesArgs and RemotesOutput values.
// You can construct a concrete instance of `RemotesInput` via:
//
//	RemotesArgs{...}
type RemotesInput interface {
	pulumi.Input

	ToRemotesOutput() RemotesOutput
	ToRemotesOutputWithContext(context.Context) RemotesOutput
}

type RemotesArgs struct {
	// The URL of the Incus host. The default will be the path to the local unix socket, or leaving it as an empty string will use the default socket path.
	Address pulumi.StringPtrInput `pulumi:"address"`
	// Server authentication type, tls or oidc. ( Only for the <span pulumi-lang-nodejs="`incus`" pulumi-lang-dotnet="`Incus`" pulumi-lang-go="`incus`" pulumi-lang-python="`incus`" pulumi-lang-yaml="`incus`" pulumi-lang-java="`incus`">`incus`</span> protocol )
	AuthenticationType pulumi.StringPtrInput `pulumi:"authenticationType"`
	// Name of the Incus remote.
	Name pulumi.StringInput `pulumi:"name"`
	// Server protocol ( incus, oci or simplestreams )
	Protocol pulumi.StringPtrInput `pulumi:"protocol"`
	// Public image server
	Public pulumi.BoolPtrInput `pulumi:"public"`
	// The trust token used for initial authentication with the Incus remote.
	Token pulumi.StringPtrInput `pulumi:"token"`
}

func (RemotesArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Remotes)(nil)).Elem()
}

func (i RemotesArgs) ToRemotesOutput() RemotesOutput {
	return i.ToRemotesOutputWithContext(context.Background())
}

func (i RemotesArgs) ToRemotesOutputWithContext(ctx context.Context) RemotesOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemotesOutput)
}

// RemotesArrayInput is an input type that accepts RemotesArray and RemotesArrayOutput values.
// You can construct a concrete instance of `RemotesArrayInput` via:
//
//	RemotesArray{ RemotesArgs{...} }
type RemotesArrayInput interface {
	pulumi.Input

	ToRemotesArrayOutput() RemotesArrayOutput
	ToRemotesArrayOutputWithContext(context.Context) RemotesArrayOutput
}

type RemotesArray []RemotesInput

func (RemotesArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Remotes)(nil)).Elem()
}

func (i RemotesArray) ToRemotesArrayOutput() RemotesArrayOutput {
	return i.ToRemotesArrayOutputWithContext(context.Background())
}

func (i RemotesArray) ToRemotesArrayOutputWithContext(ctx context.Context) RemotesArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RemotesArrayOutput)
}

type RemotesOutput struct{ *pulumi.OutputState }

func (RemotesOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Remotes)(nil)).Elem()
}

func (o RemotesOutput) ToRemotesOutput() RemotesOutput {
	return o
}

func (o RemotesOutput) ToRemotesOutputWithContext(ctx context.Context) RemotesOutput {
	return o
}

// The URL of the Incus host. The default will be the path to the local unix socket, or leaving it as an empty string will use the default socket path.
func (o RemotesOutput) Address() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Remotes) *string { return v.Address }).(pulumi.StringPtrOutput)
}

// Server authentication type, tls or oidc. ( Only for the <span pulumi-lang-nodejs="`incus`" pulumi-lang-dotnet="`Incus`" pulumi-lang-go="`incus`" pulumi-lang-python="`incus`" pulumi-lang-yaml="`incus`" pulumi-lang-java="`incus`">`incus`</span> protocol )
func (o RemotesOutput) AuthenticationType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Remotes) *string { return v.AuthenticationType }).(pulumi.StringPtrOutput)
}

// Name of the Incus remote.
func (o RemotesOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v Remotes) string { return v.Name }).(pulumi.StringOutput)
}

// Server protocol ( incus, oci or simplestreams )
func (o RemotesOutput) Protocol() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Remotes) *string { return v.Protocol }).(pulumi.StringPtrOutput)
}

// Public image server
func (o RemotesOutput) Public() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v Remotes) *bool { return v.Public }).(pulumi.BoolPtrOutput)
}

// The trust token used for initial authentication with the Incus remote.
func (o RemotesOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Remotes) *string { return v.Token }).(pulumi.StringPtrOutput)
}

type RemotesArrayOutput struct{ *pulumi.OutputState }

func (RemotesArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Remotes)(nil)).Elem()
}

func (o RemotesArrayOutput) ToRemotesArrayOutput() RemotesArrayOutput {
	return o
}

func (o RemotesArrayOutput) ToRemotesArrayOutputWithContext(ctx context.Context) RemotesArrayOutput {
	return o
}

func (o RemotesArrayOutput) Index(i pulumi.IntInput) RemotesOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Remotes {
		return vs[0].([]Remotes)[vs[1].(int)]
	}).(RemotesOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RemotesInput)(nil)).Elem(), RemotesArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*RemotesArrayInput)(nil)).Elem(), RemotesArray{})
	pulumi.RegisterOutputType(RemotesOutput{})
	pulumi.RegisterOutputType(RemotesArrayOutput{})
}
